.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.3 */


dlabel D_80063DB0
    /* 545B0 80063DB0 FFFFFF00 */ .word 0x00FFFFFF /* invalid instruction */
enddlabel D_80063DB0

glabel MdecSetVlcBufferSize
    /* 545B4 80063DB4 0680083C */ .word 0x3C088006
    /* 545B8 80063DB8 B03D0825 */  addiu      $t0, $t0, %lo(D_80063DB0)
    /* The blob stores its own load address, so the immediate must relocate
     * with the unit rather than stay the Japanese 1.0 constant. */
    /* 545BC 80063DBC FFFF8120 */ .word 0x2081FFFF
    /* 545C0 80063DC0 04002018 */ .word 0x18200004
    /* 545C4 80063DC4 0000028D */ .word 0x8D020000
    /* 545C8 80063DC8 40080400 */ .word 0x00040840
    /* 545CC 80063DCC 0800E003 */ .word 0x03E00008
    /* 545D0 80063DD0 000001AD */ .word 0xAD010000
    /* 545D4 80063DD4 FF00013C */ .word 0x3C0100FF
    /* 545D8 80063DD8 FFFF2134 */ .word 0x3421FFFF
    /* 545DC 80063DDC 0800E003 */ .word 0x03E00008
    /* 545E0 80063DE0 000001AD */ .word 0xAD010000
endlabel MdecSetVlcBufferSize

/* Handwritten function */

glabel func_80063DE4
    /* 545E4 80063DE4 0680083C */  lui        $t0, %hi(D_80063DB0)
    /* 545E8 80063DE8 B03D0825 */  addiu      $t0, $t0, %lo(D_80063DB0)
    /* 545EC 80063DEC 0880063C */  lui        $a2, %hi(D_80083048)
    /* 545F0 80063DF0 4830C624 */  addiu      $a2, $a2, %lo(D_80083048)
    /* 545F4 80063DF4 0980073C */  lui        $a3, %hi(D_80093048)
    /* 545F8 80063DF8 4830E724 */  addiu      $a3, $a3, %lo(D_80093048)
    /* 545FC 80063DFC 0F008014 */  bnez       $a0, .L80063E3C
    /* 54600 80063E00 0000098D */   lw        $t1, 0x0($t0)
    /* 54604 80063E04 0680083C */  lui        $t0, %hi(D_80064124)
    /* 54608 80063E08 24410825 */  addiu      $t0, $t0, %lo(D_80064124)
    /* 5460C 80063E0C 0000048D */  lw         $a0, 0x0($t0)
    /* 54610 80063E10 0400058D */  lw         $a1, 0x4($t0)
    /* 54614 80063E14 0800028D */  lw         $v0, 0x8($t0)
    /* 54618 80063E18 0C00038D */  lw         $v1, 0xC($t0)
    /* 5461C 80063E1C 10000C8D */  lw         $t4, 0x10($t0)
    /* 54620 80063E20 14000D8D */  lw         $t5, 0x14($t0)
    /* 54624 80063E24 1C000F8D */  lw         $t7, 0x1C($t0)
    /* 54628 80063E28 2000188D */  lw         $t8, 0x20($t0)
    /* 5462C 80063E2C 2400198D */  lw         $t9, 0x24($t0)
    /* 54630 80063E30 20482901 */  add        $t1, $t1, $t1 /* handwritten instruction */
    /* 54634 80063E34 5F000104 */  bgez       $zero, .L80063FB4
    /* 54638 80063E38 2070A900 */   add       $t6, $a1, $t1 /* handwritten instruction */
  .L80063E3C:
    /* 5463C 80063E3C 20680000 */  add        $t5, $zero, $zero /* handwritten instruction */
    /* 54640 80063E40 20780000 */  add        $t7, $zero, $zero /* handwritten instruction */
    /* 54644 80063E44 20C00000 */  add        $t8, $zero, $zero /* handwritten instruction */
    /* 54648 80063E48 20C80000 */  add        $t9, $zero, $zero /* handwritten instruction */
    /* 5464C 80063E4C 20482901 */  add        $t1, $t1, $t1 /* handwritten instruction */
    /* 54650 80063E50 2070A900 */  add        $t6, $a1, $t1 /* handwritten instruction */
    /* 54654 80063E54 00008894 */  lhu        $t0, 0x0($a0)
    /* 54658 80063E58 02008994 */  lhu        $t1, 0x2($a0)
    /* 5465C 80063E5C 04008C94 */  lhu        $t4, 0x4($a0)
    /* 54660 80063E60 06008A94 */  lhu        $t2, 0x6($a0)
    /* 54664 80063E64 08008294 */  lhu        $v0, 0x8($a0)
    /* 54668 80063E68 0A008394 */  lhu        $v1, 0xA($a0)
    /* 5466C 80063E6C FDFF4A21 */  addi       $t2, $t2, -0x3 /* handwritten instruction */
    /* 54670 80063E70 02004005 */  bltz       $t2, .L80063E7C
    /* 54674 80063E74 80620C00 */   sll       $t4, $t4, 10
    /* 54678 80063E78 01000D20 */  addi       $t5, $zero, 0x1 /* handwritten instruction */
  .L80063E7C:
    /* 5467C 80063E7C 0C008420 */  addi       $a0, $a0, 0xC /* handwritten instruction */
    /* 54680 80063E80 00140200 */  sll        $v0, $v0, 16
    /* 54684 80063E84 25104300 */  or         $v0, $v0, $v1
    /* 54688 80063E88 25180000 */  or         $v1, $zero, $zero
    /* 5468C 80063E8C 0000A8A4 */  sh         $t0, 0x0($a1)
    /* 54690 80063E90 0200A9A4 */  sh         $t1, 0x2($a1)
    /* 54694 80063E94 0200A520 */  addi       $a1, $a1, 0x2 /* handwritten instruction */
  .L80063E98:
    /* 54698 80063E98 3500A011 */  beqz       $t5, .L80063F70
    /* 5469C 80063E9C 82450200 */   srl       $t0, $v0, 22
    /* 546A0 80063EA0 FF030139 */  xori       $at, $t0, 0x3FF
    /* 546A4 80063EA4 85002010 */  beqz       $at, .L800640BC
    /* 546A8 80063EA8 0200A520 */   addi      $a1, $a1, 0x2 /* handwritten instruction */
    /* 546AC 80063EAC FDFFA121 */  addi       $at, $t5, -0x3 /* handwritten instruction */
    /* 546B0 80063EB0 02002004 */  bltz       $at, .L80063EBC
    /* 546B4 80063EB4 00FCC120 */   addi      $at, $a2, -0x400 /* handwritten instruction */
    /* 546B8 80063EB8 00FC2120 */  addi       $at, $at, -0x400 /* handwritten instruction */
  .L80063EBC:
    /* 546BC 80063EBC 02460200 */  srl        $t0, $v0, 24
    /* 546C0 80063EC0 80400800 */  sll        $t0, $t0, 2
    /* 546C4 80063EC4 20400101 */  add        $t0, $t0, $at /* handwritten instruction */
    /* 546C8 80063EC8 00000995 */  lhu        $t1, 0x0($t0)
    /* 546CC 80063ECC 02000A95 */  lhu        $t2, 0x2($t0)
    /* 546D0 80063ED0 24400000 */  and        $t0, $zero, $zero
    /* 546D4 80063ED4 0A004011 */  beqz       $t2, .L80063F00
    /* 546D8 80063ED8 04102201 */   sllv      $v0, $v0, $t1
    /* 546DC 80063EDC 20000120 */  addi       $at, $zero, 0x20 /* handwritten instruction */
    /* 546E0 80063EE0 22082A00 */  sub        $at, $at, $t2 /* handwritten instruction */
    /* 546E4 80063EE4 06402200 */  srlv       $t0, $v0, $at
    /* 546E8 80063EE8 04004004 */  bltz       $v0, .L80063EFC
    /* 546EC 80063EEC 04104201 */   sllv      $v0, $v0, $t2
    /* 546F0 80063EF0 FFFF0B20 */  addi       $t3, $zero, -0x1 /* handwritten instruction */
    /* 546F4 80063EF4 06582B00 */  srlv       $t3, $t3, $at
    /* 546F8 80063EF8 22400B01 */  sub        $t0, $t0, $t3 /* handwritten instruction */
  .L80063EFC:
    /* 546FC 80063EFC 20186A00 */  add        $v1, $v1, $t2 /* handwritten instruction */
  .L80063F00:
    /* 54700 80063F00 20186900 */  add        $v1, $v1, $t1 /* handwritten instruction */
    /* 54704 80063F04 10006130 */  andi       $at, $v1, 0x10
    /* 54708 80063F08 05002010 */  beqz       $at, .L80063F20
    /* 5470C 80063F0C 0F006330 */   andi      $v1, $v1, 0xF
    /* 54710 80063F10 00008994 */  lhu        $t1, 0x0($a0)
    /* 54714 80063F14 02008420 */  addi       $a0, $a0, 0x2 /* handwritten instruction */
    /* 54718 80063F18 04486900 */  sllv       $t1, $t1, $v1
    /* 5471C 80063F1C 25104900 */  or         $v0, $v0, $t1
  .L80063F20:
    /* 54720 80063F20 FEFFA121 */  addi       $at, $t5, -0x2 /* handwritten instruction */
    /* 54724 80063F24 0800201C */  bgtz       $at, .L80063F48
    /* 54728 80063F28 20482803 */   add       $t1, $t9, $t0 /* handwritten instruction */
    /* 5472C 80063F2C 04002010 */  beqz       $at, .L80063F40
    /* 54730 80063F30 20480803 */   add       $t1, $t8, $t0 /* handwritten instruction */
    /* 54734 80063F34 2048E801 */  add        $t1, $t7, $t0 /* handwritten instruction */
    /* 54738 80063F38 04000104 */  bgez       $zero, .L80063F4C
    /* 5473C 80063F3C 2078E801 */   add       $t7, $t7, $t0 /* handwritten instruction */
  .L80063F40:
    /* 54740 80063F40 02000104 */  bgez       $zero, .L80063F4C
    /* 54744 80063F44 20C00803 */   add       $t8, $t8, $t0 /* handwritten instruction */
  .L80063F48:
    /* 54748 80063F48 20C82803 */  add        $t9, $t9, $t0 /* handwritten instruction */
  .L80063F4C:
    /* 5474C 80063F4C 80480900 */  sll        $t1, $t1, 2
    /* 54750 80063F50 FF032931 */  andi       $t1, $t1, 0x3FF
    /* 54754 80063F54 25488901 */  or         $t1, $t4, $t1
    /* 54758 80063F58 0100AD21 */  addi       $t5, $t5, 0x1 /* handwritten instruction */
    /* 5475C 80063F5C F9FFA121 */  addi       $at, $t5, -0x7 /* handwritten instruction */
    /* 54760 80063F60 11002014 */  bnez       $at, .L80063FA8
    /* 54764 80063F64 0000A9A4 */   sh        $t1, 0x0($a1)
    /* 54768 80063F68 0F000104 */  bgez       $zero, .L80063FA8
    /* 5476C 80063F6C FAFFAD21 */   addi      $t5, $t5, -0x6 /* handwritten instruction */
  .L80063F70:
    /* 54770 80063F70 FF010139 */  xori       $at, $t0, 0x1FF
    /* 54774 80063F74 51002010 */  beqz       $at, .L800640BC
    /* 54778 80063F78 0200A520 */   addi      $a1, $a1, 0x2 /* handwritten instruction */
    /* 5477C 80063F7C 80120200 */  sll        $v0, $v0, 10
    /* 54780 80063F80 0A006320 */  addi       $v1, $v1, 0xA /* handwritten instruction */
    /* 54784 80063F84 10006130 */  andi       $at, $v1, 0x10
    /* 54788 80063F88 05002010 */  beqz       $at, .L80063FA0
    /* 5478C 80063F8C 0F006330 */   andi      $v1, $v1, 0xF
    /* 54790 80063F90 00008994 */  lhu        $t1, 0x0($a0)
    /* 54794 80063F94 02008420 */  addi       $a0, $a0, 0x2 /* handwritten instruction */
    /* 54798 80063F98 04486900 */  sllv       $t1, $t1, $v1
    /* 5479C 80063F9C 25104900 */  or         $v0, $v0, $t1
  .L80063FA0:
    /* 547A0 80063FA0 25408801 */  or         $t0, $t4, $t0
    /* 547A4 80063FA4 0000A8A4 */  sh         $t0, 0x0($a1)
  .L80063FA8:
    /* 547A8 80063FA8 2308AE00 */  subu       $at, $a1, $t6
    /* 547AC 80063FAC 50002104 */  bgez       $at, .L800640F0
    /* 547B0 80063FB0 0200A520 */   addi      $a1, $a1, 0x2 /* handwritten instruction */
  .L80063FB4:
    /* 547B4 80063FB4 C2440200 */  srl        $t0, $v0, 19
    /* 547B8 80063FB8 C0400800 */  sll        $t0, $t0, 3
    /* 547BC 80063FBC 20400601 */  add        $t0, $t0, $a2 /* handwritten instruction */
    /* 547C0 80063FC0 0000098D */  lw         $t1, 0x0($t0)
    /* 547C4 80063FC4 00000000 */  nop
    /* 547C8 80063FC8 11002015 */  bnez       $t1, .L80064010
    /* 547CC 80063FCC FF002131 */   andi      $at, $t1, 0xFF
    /* 547D0 80063FD0 00120200 */  sll        $v0, $v0, 8
    /* 547D4 80063FD4 08006320 */  addi       $v1, $v1, 0x8 /* handwritten instruction */
    /* 547D8 80063FD8 10006130 */  andi       $at, $v1, 0x10
    /* 547DC 80063FDC 05002010 */  beqz       $at, .L80063FF4
    /* 547E0 80063FE0 0F006330 */   andi      $v1, $v1, 0xF
    /* 547E4 80063FE4 00008894 */  lhu        $t0, 0x0($a0)
    /* 547E8 80063FE8 02008420 */  addi       $a0, $a0, 0x2 /* handwritten instruction */
    /* 547EC 80063FEC 04406800 */  sllv       $t0, $t0, $v1
    /* 547F0 80063FF0 25104800 */  or         $v0, $v0, $t0
  .L80063FF4:
    /* 547F4 80063FF4 C2450200 */  srl        $t0, $v0, 23
    /* 547F8 80063FF8 80400800 */  sll        $t0, $t0, 2
    /* 547FC 80063FFC 20400701 */  add        $t0, $t0, $a3 /* handwritten instruction */
    /* 54800 80064000 0000098D */  lw         $t1, 0x0($t0)
    /* 54804 80064004 20580000 */  add        $t3, $zero, $zero /* handwritten instruction */
    /* 54808 80064008 02000104 */  bgez       $zero, .L80064014
    /* 5480C 8006400C FF002131 */   andi      $at, $t1, 0xFF
  .L80064010:
    /* 54810 80064010 04000B8D */  lw         $t3, 0x4($t0)
  .L80064014:
    /* 54814 80064014 04102200 */  sllv       $v0, $v0, $at
    /* 54818 80064018 20186100 */  add        $v1, $v1, $at /* handwritten instruction */
    /* 5481C 8006401C 10006130 */  andi       $at, $v1, 0x10
    /* 54820 80064020 05002010 */  beqz       $at, .L80064038
    /* 54824 80064024 0F006330 */   andi      $v1, $v1, 0xF
    /* 54828 80064028 00008894 */  lhu        $t0, 0x0($a0)
    /* 5482C 8006402C 02008420 */  addi       $a0, $a0, 0x2 /* handwritten instruction */
    /* 54830 80064030 04406800 */  sllv       $t0, $t0, $v1
    /* 54834 80064034 25104800 */  or         $v0, $v0, $t0
  .L80064038:
    /* 54838 80064038 024C0900 */  srl        $t1, $t1, 16
    /* 5483C 8006403C 1F7C2139 */  xori       $at, $t1, 0x7C1F
    /* 54840 80064040 15002010 */  beqz       $at, .L80064098
    /* 54844 80064044 00FE2139 */   xori      $at, $t1, 0xFE00
    /* 54848 80064048 93FF2010 */  beqz       $at, .L80063E98
    /* 5484C 8006404C 0000A9A4 */   sh        $t1, 0x0($a1)
    /* 54850 80064050 D8FF6011 */  beqz       $t3, .L80063FB4
    /* 54854 80064054 0200A520 */   addi      $a1, $a1, 0x2 /* handwritten instruction */
    /* 54858 80064058 FFFF6A31 */  andi       $t2, $t3, 0xFFFF
    /* 5485C 8006405C 1F7C4139 */  xori       $at, $t2, 0x7C1F
    /* 54860 80064060 0D002010 */  beqz       $at, .L80064098
    /* 54864 80064064 00FE4139 */   xori      $at, $t2, 0xFE00
    /* 54868 80064068 8BFF2010 */  beqz       $at, .L80063E98
    /* 5486C 8006406C 0000AAA4 */   sh        $t2, 0x0($a1)
    /* 54870 80064070 02540B00 */  srl        $t2, $t3, 16
    /* 54874 80064074 CFFF4011 */  beqz       $t2, .L80063FB4
    /* 54878 80064078 0200A520 */   addi      $a1, $a1, 0x2 /* handwritten instruction */
    /* 5487C 8006407C 1F7C4139 */  xori       $at, $t2, 0x7C1F
    /* 54880 80064080 05002010 */  beqz       $at, .L80064098
    /* 54884 80064084 00FE4139 */   xori      $at, $t2, 0xFE00
    /* 54888 80064088 83FF2010 */  beqz       $at, .L80063E98
    /* 5488C 8006408C 0000AAA4 */   sh        $t2, 0x0($a1)
    /* 54890 80064090 C8FF0104 */  bgez       $zero, .L80063FB4
    /* 54894 80064094 0200A520 */   addi      $a1, $a1, 0x2 /* handwritten instruction */
  .L80064098:
    /* 54898 80064098 02440200 */  srl        $t0, $v0, 16
    /* 5489C 8006409C 0000A8A4 */  sh         $t0, 0x0($a1)
    /* 548A0 800640A0 0200A520 */  addi       $a1, $a1, 0x2 /* handwritten instruction */
    /* 548A4 800640A4 00008894 */  lhu        $t0, 0x0($a0)
    /* 548A8 800640A8 02008420 */  addi       $a0, $a0, 0x2 /* handwritten instruction */
    /* 548AC 800640AC 00140200 */  sll        $v0, $v0, 16
    /* 548B0 800640B0 04406800 */  sllv       $t0, $t0, $v1
    /* 548B4 800640B4 BFFF0104 */  bgez       $zero, .L80063FB4
    /* 548B8 800640B8 25104800 */   or        $v0, $v0, $t0
  .L800640BC:
    /* 548BC 800640BC 00FE0834 */  ori        $t0, $zero, 0xFE00
    /* 548C0 800640C0 40000220 */  addi       $v0, $zero, 0x40 /* handwritten instruction */
  .L800640C4:
    /* 548C4 800640C4 0000A8A4 */  sh         $t0, 0x0($a1)
    /* 548C8 800640C8 0200A520 */  addi       $a1, $a1, 0x2 /* handwritten instruction */
    /* 548CC 800640CC FDFF4014 */  bnez       $v0, .L800640C4
    /* 548D0 800640D0 FFFF4220 */   addi      $v0, $v0, -0x1 /* handwritten instruction */
    /* 548D4 800640D4 00600940 */  mfc0       $t1, $12 /* handwritten instruction */
    /* 548D8 800640D8 00000000 */  nop
    /* 548DC 800640DC 0200013C */  lui        $at, (0x20000 >> 16)
    /* 548E0 800640E0 25482101 */  or         $t1, $t1, $at
    /* 548E4 800640E4 00608940 */  mtc0       $t1, $12 /* handwritten instruction */
    /* 548E8 800640E8 0800E003 */  jr         $ra
    /* 548EC 800640EC 20100000 */   add       $v0, $zero, $zero /* handwritten instruction */
  .L800640F0:
    /* 548F0 800640F0 0680083C */  lui        $t0, %hi(D_80064124)
    /* 548F4 800640F4 24410825 */  addiu      $t0, $t0, %lo(D_80064124)
    /* 548F8 800640F8 000004AD */  sw         $a0, 0x0($t0)
    /* 548FC 800640FC 040005AD */  sw         $a1, 0x4($t0)
    /* 54900 80064100 080002AD */  sw         $v0, 0x8($t0)
    /* 54904 80064104 0C0003AD */  sw         $v1, 0xC($t0)
    /* 54908 80064108 10000CAD */  sw         $t4, 0x10($t0)
    /* 5490C 8006410C 14000DAD */  sw         $t5, 0x14($t0)
    /* 54910 80064110 1C000FAD */  sw         $t7, 0x1C($t0)
    /* 54914 80064114 200018AD */  sw         $t8, 0x20($t0)
    /* 54918 80064118 240019AD */  sw         $t9, 0x24($t0)
    /* 5491C 8006411C 0800E003 */  jr         $ra
    /* 54920 80064120 01000220 */   addi      $v0, $zero, 0x1 /* handwritten instruction */
endlabel func_80063DE4
dlabel D_80064124
    /* 54924 80064124 00000000 */  nop
    /* 54928 80064128 00000000 */  nop
    /* 5492C 8006412C 00000000 */  nop
    /* 54930 80064130 00000000 */  nop
    /* 54934 80064134 00000000 */  nop
    /* 54938 80064138 00000000 */  nop
    /* 5493C 8006413C 00000000 */  nop
    /* 54940 80064140 00000000 */  nop
    /* 54944 80064144 00000000 */  nop
enddlabel D_80064124
