#!/usr/bin/env python3
"""Give the program's bss objects real definitions instead of pinned addresses.

Every uninitialised global lives past the end of the image, so splat cannot see
it and emits nothing for it.  The references from .text survive as undefined
``D_<vram>`` symbols, and both ``undefined_syms_auto`` and
``undefined_addr_aliases`` then pin each one to the literal address baked into
its name.  That is what stops the program from being relocatable: the moment
.text or .data changes size every one of those addresses is wrong.

This script replaces the pins with an ordinary NOLOAD input section.  It reads
``configs/<version>/bss.<basename>.txt`` -- a tracked, human-readable table of
``original-vram symbol size`` in address order -- and emits an assembly file
that lays the same objects out *relative to the start of bss*.  The linker then
places them wherever bss happens to begin, so they follow .text and .data
instead of anchoring them.

Because .text reaches these objects through %hi/%lo relocation pairs, the
rebuilt image is byte-identical only if every offset in the table is right, so
``make check`` doubles as a proof of the layout.

Run after splat, from ``make split``.
"""
from __future__ import annotations

import argparse
from pathlib import Path

MARKER = "/* bss objects, laid out by tools/scripts/gen_bss.py. */"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", default="PAL")
    parser.add_argument("--basename", default="main")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    return parser.parse_args()


def read_layout(path: Path) -> tuple[int, list[tuple[int, str, int]]]:
    base: int | None = None
    entries: list[tuple[int, str, int]] = []
    for lineno, raw in enumerate(path.read_text(encoding="ascii").splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if line.startswith("base "):
            base = int(line.split()[1], 16)
            continue
        addr_s, name, size_s = line.split()
        addr, size = int(addr_s, 16), int(size_s, 16)
        if base is None:
            raise SystemExit(f"{path}:{lineno}: entry before `base`")
        if size <= 0:
            raise SystemExit(f"{path}:{lineno}: non-positive size")
        entries.append((addr, name, size))
    if base is None:
        raise SystemExit(f"{path}: no `base` line")

    # The table is only trustworthy if it tiles the region exactly: a hole or an
    # overlap would silently shift every later object.
    cursor = base
    for addr, name, size in entries:
        if addr != cursor:
            raise SystemExit(
                f"{path}: {name} starts at 0x{addr:08X}, expected 0x{cursor:08X}"
            )
        cursor += size
    return base, entries


def emit_asm(base: int, entries: list[tuple[int, str, int]], out: Path) -> int:
    lines = [
        "/* Generated by tools/scripts/gen_bss.py -- do not edit. */",
        "/* Layout source: configs/<version>/bss.<basename>.txt */",
        "",
        ".section .bss",
        "",
    ]
    defined = 0
    for addr, name, size in entries:
        lines.append(f"/* {addr:08X} */")
        if name != ".":
            lines.append(f".globl {name}")
            lines.append(f"{name}:")
            defined += 1
        lines.append(f".space 0x{size:X}")
        lines.append("")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="ascii")
    return defined


def patch_linker_script(ld: Path, obj: str) -> None:
    text = ld.read_text(encoding="utf-8")
    if MARKER in text:
        return
    needle = "        main_BSS_START = .;\n"
    if needle not in text:
        raise SystemExit(f"{ld}: no main_BSS_START anchor")
    text = text.replace(
        needle,
        needle + f"        {MARKER}\n        {obj}(.bss);\n",
        1,
    )
    ld.write_text(text, encoding="utf-8")


def main() -> int:
    args = parse_args()
    root: Path = args.root
    layout = root / "configs" / args.version / f"bss.{args.basename}.txt"
    if not layout.exists():
        return 0

    base, entries = read_layout(layout)
    asm_rel = f"asm/{args.version}/{args.basename}/bss.s"
    defined = emit_asm(base, entries, root / asm_rel)

    obj = f"build/{args.version}/{asm_rel}.o"
    patch_linker_script(root / "linkers" / args.version / f"{args.basename}.ld", obj)

    end = base + sum(size for _, _, size in entries)
    print(
        f"gen_bss: {defined} objects over 0x{base:08X}..0x{end:08X}"
        f" ({end - base} bytes)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
