#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from datetime import date
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
VERSION = "PAL"
CONFIG = ROOT / "configs" / VERSION / "main.yaml"
SRC_ROOT = ROOT / "src" / "main"
DOCS = ROOT / "docs"
BADGES = DOCS / "badges"


ASM_MARKERS = re.compile(
    r"INCLUDE_ASM|INCLUDE_RODATA|\.word|\.globl|\.ent|\.include"
)
ASM_RE = re.compile(r"(^|[^_a-zA-Z0-9])(__asm__|asm)\b")
SUBSEGMENT = re.compile(
    r"\[0x([0-9A-Fa-f]+),\s*([^,\]\s]+),\s*([^,\]\s]+)"
)


def color(percent: float) -> str:
    if percent >= 90:
        return "brightgreen"
    if percent >= 60:
        return "green"
    if percent >= 30:
        return "yellow"
    if percent >= 10:
        return "orange"
    return "red"


def badge(path: Path, label: str, message: str, percent: float) -> None:
    path.write_text(
        json.dumps(
            {
                "schemaVersion": 1,
                "label": label,
                "message": message,
                "color": color(percent),
            },
            indent=2,
        )
        + "\n"
    )


def strip_comments(text: str) -> str:
    return re.sub(r"//.*", "", re.sub(r"/\*.*?\*/", "", text, flags=re.S))


def strip_nonblocking_asm(text: str) -> str:
    decl_label = r"(?m)(^.*\S\s+)\b(?:__asm__|asm)\s*\(\s*\"(?:[^\"\\]|\\.)*\"\s*\)"
    text = re.sub(decl_label, r"\1", text)

    empty = r"\b(?:__asm__|asm)\s*(?:__volatile__|volatile)?\s*\(\s*\"\"\s*(?::.*?)?\)\s*;"
    return re.sub(empty, "", text, flags=re.S)


def is_plain_c(path: Path) -> bool:
    if not path.exists():
        return False
    text = strip_nonblocking_asm(strip_comments(path.read_text(errors="ignore")))
    return ASM_MARKERS.search(text) is None and ASM_RE.search(text) is None


def main() -> int:
    subsegments = []
    for line in CONFIG.read_text().splitlines():
        match = SUBSEGMENT.search(line)
        if match:
            subsegments.append((int(match.group(1), 16), match.group(2), match.group(3)))

    rows = []
    total_funcs = 0
    plain_funcs = 0
    total_bytes = 0
    plain_bytes = 0

    for index, (start, kind, name) in enumerate(subsegments):
        if kind != "c":
            continue
        end = None
        for next_start, _next_kind, _next_name in subsegments[index + 1 :]:
            end = next_start
            break
        if end is None:
            continue

        size = max(0, end - start)
        src = SRC_ROOT / f"{name}.c"
        plain = is_plain_c(src)

        total_funcs += 1
        total_bytes += size
        if plain:
            plain_funcs += 1
            plain_bytes += size

    func_pct = plain_funcs / total_funcs * 100 if total_funcs else 0.0
    byte_pct = plain_bytes / total_bytes * 100 if total_bytes else 0.0
    rows.append(
        (
            "`SCES_006.50 (main)`",
            f"{plain_funcs}/{total_funcs}",
            f"{func_pct:.1f}%",
            f"{plain_bytes}/{total_bytes}",
            f"{byte_pct:.1f}%",
        )
    )

    DOCS.mkdir(exist_ok=True)
    BADGES.mkdir(exist_ok=True)

    badge(
        BADGES / "functions.json",
        "functions",
        f"{plain_funcs}/{total_funcs} {func_pct:.1f}%",
        func_pct,
    )
    badge(
        BADGES / "code.json",
        "code",
        f"{plain_bytes}/{total_bytes} {byte_pct:.1f}%",
        byte_pct,
    )

    lines = [
        "# Decompilation Progress",
        "",
        f"_Generated by `tools/scripts/progress_report.py` on {date.today().isoformat()}. Regenerate with `make progress`._",
        "",
        "A translation unit counts as decompiled when it has no INCLUDE_ASM/INCLUDE_RODATA and no non-empty inline assembly. Register/symbol asm labels and empty barriers used for matching do not lower progress. Code bytes cover function subsegments only. The built executable is byte-identical to retail (`make check VERSION=PAL`).",
        "",
        "| Binary | Functions | % | Code bytes | % |",
        "|---|---:|---:|---:|---:|",
    ]
    lines.extend(f"| {binary} | {funcs} | {fpct} | {code} | {bpct} |" for binary, funcs, fpct, code, bpct in rows)
    (DOCS / "PROGRESS.md").write_text("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
