name: Main Executable (SLUS_004.03) - Rage Racer (USA)
sha1: 2661e8bf18d209c98fd70d33e18ab88b10abd52b
options:
  basename: main
  target_path: assets/USA/main.exe
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/main
  src_path: src/main
  build_path: build/USA
  ld_script_path: linkers/USA/main.ld

  migrate_rodata_to_functions: False
  find_file_boundaries: True

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  generate_asm_macros_files: False

  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
  reloc_addrs_path:
    - configs/USA/rel.main.txt

  undefined_funcs_auto_path: linkers/USA/undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/USA/undefined_syms_auto.main.txt

  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
  ld_bss_is_noload: True

# PS-X EXE layout for SLUS_004.03:
#   header   0x000000 - 0x000800
#   .text   @ vram 0x80010000, size 0x8B000, ends @ 0x8009B000
#   entry PC = 0x80062DC4
#   stack top = 0x801FFFF0
segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80010000
    align: 4
    subalign: 4
    bss_size: 0x0
    subsegments:
      - [0x800, asm, main/000800_main]
      - [0x8B800]
