.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.3 */


glabel D_80062910
    /* 53110 80062910 0A80023C */ .word 0x3C02800A
    /* 53114 80062914 80A54224 */ .word 0x2442A668
    /* 53118 80062918 1F80033C */ .word 0x3C03801F
    /* 5311C 8006291C A43C6324 */ .word 0x24633DBC
    /* 53120 80062920 000040AC */ .word 0xAC400000
    /* 53124 80062924 04004224 */ .word 0x24420004
    /* 53128 80062928 2B084300 */ .word 0x0043082B
    /* 5312C 8006292C FCFF2014 */ .word 0x1420FFFC
    /* 53130 80062930 00000000 */ .word 0x00000000
    /* 53134 80062934 04000224 */ .word 0x24020004
    /* 53138 80062938 00000000 */ .word 0x00000000
    /* 5313C 8006293C 00000000 */ .word 0x00000000
    /* 53140 80062940 00000000 */ .word 0x00000000
    /* 53144 80062944 00000000 */ .word 0x00000000
    /* 53148 80062948 0680043C */ .word 0x3C048006
    /* 5314C 8006294C BC298424 */ .word 0x24842AA4
    /* 53150 80062950 21208200 */ .word 0x00822021
    /* 53154 80062954 0000828C */ .word 0x8C820000
    /* 53158 80062958 0080083C */ .word 0x3C088000
    /* 5315C 8006295C 25E84800 */ .word 0x0048E825
    /* 53160 80062960 1F80043C */ .word 0x3C04801F
    /* 53164 80062964 A43C8424 */ .word 0x24843DBC
    /* 53168 80062968 C0200400 */ .word 0x000420C0
    /* 5316C 8006296C C2200400 */ .word 0x000420C2
    /* 53170 80062970 0A80033C */ .word 0x3C03800A
    /* 53174 80062974 C89B638C */ .word 0x8C639CB0
    /* 53178 80062978 00000000 */ .word 0x00000000
    /* 5317C 8006297C 23284300 */ .word 0x00432823
    /* 53180 80062980 2328A400 */ .word 0x00A42823
    /* 53184 80062984 25208800 */ .word 0x00882025
    /* 53188 80062988 0A80013C */ .word 0x3C01800A
    /* 5318C 8006298C 80A53FAC */ .word 0xAC3FA668
    /* 53190 80062990 0A801C3C */ .word 0x3C1C800A
    /* 53194 80062994 80A59C27 */ .word 0x279CA668
    /* 53198 80062998 21F0A003 */ .word 0x03A0F021
    /* 5319C 8006299C 738A010C */ .word 0x0C018AAD
    /* 531A0 800629A0 04008420 */ .word 0x20840004
    /* 531A4 800629A4 0A801F3C */ .word 0x3C1F800A
    /* 531A8 800629A8 80A5FF8F */ .word 0x8FFFA668
    /* 531AC 800629AC 00000000 */ .word 0x00000000
    /* 531B0 800629B0 E058000C */ .word 0x0C0058E1
    /* 531B4 800629B4 00000000 */ .word 0x00000000
    /* 531B8 800629B8 4D000000 */ .word 0x0000004D
endlabel D_80062910

/* Four stack-top addresses loaded by the startup code above. */
dlabel g_BootStackTops
    /* 531BC 800629BC 00002000 */ .word 0x00200000
    /* 531C0 800629C0 00002000 */ .word 0x00200000 /* invalid instruction */
    /* 531C4 800629C4 00002000 */ .word 0x00200000 /* invalid instruction */
    /* 531C8 800629C8 00002000 */ .word 0x00200000
enddlabel g_BootStackTops


.global func_800629CC
.type func_800629CC, @function
func_800629CC:
.size func_800629CC, 12
    /* 531CC 800629CC A0000A24 */ .word 0x240A00A0
    /* 531D0 800629D0 08004001 */ .word 0x01400008
    /* 531D4 800629D4 39000924 */ .word 0x24090039
    /* 531D8 800629D8 00000000 */ .word 0x00000000


.global BiosBuInit
.type BiosBuInit, @function
BiosBuInit:
.size BiosBuInit, 12
    /* 531DC 800629DC A0000A24 */ .word 0x240A00A0
    /* 531E0 800629E0 08004001 */ .word 0x01400008
    /* 531E4 800629E4 70000924 */ .word 0x24090070
    /* 531E8 800629E8 00000000 */ .word 0x00000000


.global BiosSetMemSize
.type BiosSetMemSize, @function
BiosSetMemSize:
.size BiosSetMemSize, 12
    /* 531EC 800629EC A0000A24 */ .word 0x240A00A0
    /* 531F0 800629F0 08004001 */ .word 0x01400008
    /* 531F4 800629F4 9F000924 */ .word 0x2409009F
    /* 531F8 800629F8 00000000 */ .word 0x00000000


.global OpenEvent
.type OpenEvent, @function
OpenEvent:
.size OpenEvent, 12
    /* 531FC 800629FC B0000A24 */ .word 0x240A00B0
    /* 53200 80062A00 08004001 */ .word 0x01400008
    /* 53204 80062A04 08000924 */ .word 0x24090008
    /* 53208 80062A08 00000000 */ .word 0x00000000


.global CloseEvent
.type CloseEvent, @function
CloseEvent:
.size CloseEvent, 12
    /* 5320C 80062A0C B0000A24 */ .word 0x240A00B0
    /* 53210 80062A10 08004001 */ .word 0x01400008
    /* 53214 80062A14 09000924 */ .word 0x24090009
    /* 53218 80062A18 00000000 */ .word 0x00000000


.global TestEvent
.type TestEvent, @function
TestEvent:
.size TestEvent, 12
    /* 5321C 80062A1C B0000A24 */ .word 0x240A00B0
    /* 53220 80062A20 08004001 */ .word 0x01400008
    /* 53224 80062A24 0B000924 */ .word 0x2409000B
    /* 53228 80062A28 00000000 */ .word 0x00000000


.global EnableEvent
.type EnableEvent, @function
EnableEvent:
.size EnableEvent, 12
    /* 5322C 80062A2C B0000A24 */ .word 0x240A00B0
    /* 53230 80062A30 08004001 */ .word 0x01400008
    /* 53234 80062A34 0C000924 */ .word 0x2409000C
    /* 53238 80062A38 00000000 */ .word 0x00000000


.global DisableEvent
.type DisableEvent, @function
DisableEvent:
.size DisableEvent, 12
    /* 5323C 80062A3C B0000A24 */ .word 0x240A00B0
    /* 53240 80062A40 08004001 */ .word 0x01400008
    /* 53244 80062A44 0D000924 */ .word 0x2409000D
    /* 53248 80062A48 00000000 */ .word 0x00000000


.global InitPad
.type InitPad, @function
InitPad:
.size InitPad, 12
    /* 5324C 80062A4C B0000A24 */ .word 0x240A00B0
    /* 53250 80062A50 08004001 */ .word 0x01400008
    /* 53254 80062A54 12000924 */ .word 0x24090012
    /* 53258 80062A58 00000000 */ .word 0x00000000


.global StartPad
.type StartPad, @function
StartPad:
.size StartPad, 12
    /* 5325C 80062A5C B0000A24 */ .word 0x240A00B0
    /* 53260 80062A60 08004001 */ .word 0x01400008
    /* 53264 80062A64 13000924 */ .word 0x24090013
    /* 53268 80062A68 00000000 */ .word 0x00000000


.global EnterCriticalSection
.type EnterCriticalSection, @function
EnterCriticalSection:
.size EnterCriticalSection, 16
    /* 5326C 80062A6C 01000424 */ .word 0x24040001
    /* 53270 80062A70 0C000000 */ .word 0x0000000C
    /* 53274 80062A74 0800E003 */ .word 0x03E00008
    /* 53278 80062A78 00000000 */ .word 0x00000000

/* Handwritten function */

glabel ExitCriticalSection
    /* 5327C 80062A7C 02000424 */  addiu      $a0, $zero, 0x2
    /* 53280 80062A80 0C000000 */  syscall    0 /* handwritten instruction */
    /* 53284 80062A84 0800E003 */  jr         $ra
    /* 53288 80062A88 00000000 */   nop
endlabel ExitCriticalSection
