#ifndef RAGE_PC_GAME_SEQUENCE_H
#define RAGE_PC_GAME_SEQUENCE_H

#include "psyq/snd.h"

#define SEQUENCE_STATE_STRIDE 0xAC
#define SEQUENCE_CHANNEL_COUNT SS_SEQUENCE_CHANNEL_COUNT

#define SEQUENCE_FLAG_PLAYING SS_SEQ_FLAG_PLAYING
#define SEQUENCE_FLAG_PAUSED SS_SEQ_FLAG_PAUSED
#define SEQUENCE_FLAG_STOPPED SS_SEQ_FLAG_STOPPED
#define SEQUENCE_FLAG_8 SS_SEQ_FLAG_8
#define SEQUENCE_FLAG_TEMPO_DEC SS_SEQ_FLAG_TEMPO_DEC
#define SEQUENCE_FLAG_TEMPO_INC SS_SEQ_FLAG_TEMPO_INC
#define SEQUENCE_FLAG_100 0x100
#define SEQUENCE_FLAG_200 0x200
#define SEQUENCE_FLAG_400 0x400

#endif
