#ifndef GAME_TRACK_CAMERA_INTERNAL_H
#define GAME_TRACK_CAMERA_INTERNAL_H

#include "common.h"

#ifndef GAME_TRACK_CAMERA_TYPE
#define GAME_TRACK_CAMERA_TYPE void
#endif
extern GAME_TRACK_CAMERA_TYPE *g_TrackCameras;
#undef GAME_TRACK_CAMERA_TYPE
#ifndef GAME_TRACK_SECTION_COUNT_TYPE
#define GAME_TRACK_SECTION_COUNT_TYPE s16
#endif
extern GAME_TRACK_SECTION_COUNT_TYPE g_TrackSectionCount;
#undef GAME_TRACK_SECTION_COUNT_TYPE

#endif
