.include "macro.inc"

.set noat
.set noreorder

.section .text, "ax"

/* Generated by spimdisasm 1.42.3 */

/* Handwritten function */
nonmatching SquareRoot0, 0x84

glabel SquareRoot0
    /* 58A04 80068204 00F08448 */  mtc2       $a0, $30 /* handwritten instruction */
    /* 58A08 80068208 00000000 */  nop
    /* 58A0C 8006820C 00000000 */  nop
    /* 58A10 80068210 00F80248 */  mfc2       $v0, $31 /* handwritten instruction */
    /* 58A14 80068214 20000124 */  addiu      $at, $zero, 0x20
    /* 58A18 80068218 19004110 */  beq        $v0, $at, .L80068280
    /* 58A1C 8006821C 00000000 */   nop
    /* 58A20 80068220 01004830 */  andi       $t0, $v0, 0x1
    /* 58A24 80068224 FEFF0A24 */  addiu      $t2, $zero, -0x2
    /* 58A28 80068228 24504A00 */  and        $t2, $v0, $t2
    /* 58A2C 8006822C 1F000924 */  addiu      $t1, $zero, 0x1F
    /* 58A30 80068230 22482A01 */  sub        $t1, $t1, $t2 /* handwritten instruction */
    /* 58A34 80068234 43480900 */  sra        $t1, $t1, 1
    /* 58A38 80068238 E8FF4B21 */  addi       $t3, $t2, -0x18 /* handwritten instruction */
    /* 58A3C 8006823C 03006005 */  bltz       $t3, .L8006824C
    /* 58A40 80068240 00000000 */   nop
    /* 58A44 80068244 04606401 */  sllv       $t4, $a0, $t3
    /* 58A48 80068248 03000010 */  b          .L80068258
  .L8006824C:
    /* 58A4C 8006824C 18000B24 */   addiu     $t3, $zero, 0x18
    /* 58A50 80068250 22586A01 */  sub        $t3, $t3, $t2 /* handwritten instruction */
    /* 58A54 80068254 07606401 */  srav       $t4, $a0, $t3
  .L80068258:
    /* 58A58 80068258 C0FF8C21 */  addi       $t4, $t4, -0x40 /* handwritten instruction */
    /* 58A5C 8006825C 40600C00 */  sll        $t4, $t4, 1
    /* 58A60 80068260 09800D3C */  lui        $t5, %hi(D_800941C4)
    /* 58A64 80068264 2168AC01 */  addu       $t5, $t5, $t4
    /* 58A68 80068268 C441AD85 */  lh         $t5, %lo(D_800941C4)($t5)
    /* 58A6C 8006826C 00000000 */  nop
    /* 58A70 80068270 04682D01 */  sllv       $t5, $t5, $t1
    /* 58A74 80068274 02130D00 */  srl        $v0, $t5, 12
    /* 58A78 80068278 0800E003 */  jr         $ra
    /* 58A7C 8006827C 00000000 */   nop
  .L80068280:
    /* 58A80 80068280 0800E003 */  jr         $ra
    /* 58A84 80068284 00000224 */   addiu     $v0, $zero, 0x0
endlabel SquareRoot0
    /* 58A88 80068288 00000000 */  nop
    /* 58A8C 8006828C 00000000 */  nop
    /* 58A90 80068290 00000000 */  nop

/* Handwritten function */
nonmatching CompMatrix, 0x160

glabel CompMatrix
    /* 58A94 80068294 0000888C */  lw         $t0, 0x0($a0)
    /* 58A98 80068298 0400898C */  lw         $t1, 0x4($a0)
    /* 58A9C 8006829C 08008A8C */  lw         $t2, 0x8($a0)
    /* 58AA0 800682A0 0C008B8C */  lw         $t3, 0xC($a0)
    /* 58AA4 800682A4 10008C8C */  lw         $t4, 0x10($a0)
    /* 58AA8 800682A8 0000C848 */  ctc2       $t0, $0 /* handwritten instruction */
    /* 58AAC 800682AC 0008C948 */  ctc2       $t1, $1 /* handwritten instruction */
    /* 58AB0 800682B0 0010CA48 */  ctc2       $t2, $2 /* handwritten instruction */
    /* 58AB4 800682B4 0018CB48 */  ctc2       $t3, $3 /* handwritten instruction */
    /* 58AB8 800682B8 0020CC48 */  ctc2       $t4, $4 /* handwritten instruction */
    /* 58ABC 800682BC 0000A894 */  lhu        $t0, 0x0($a1)
    /* 58AC0 800682C0 0400A98C */  lw         $t1, 0x4($a1)
    /* 58AC4 800682C4 0C00AA8C */  lw         $t2, 0xC($a1)
    /* 58AC8 800682C8 FFFF013C */  lui        $at, (0xFFFF0000 >> 16)
    /* 58ACC 800682CC 24482101 */  and        $t1, $t1, $at
    /* 58AD0 800682D0 25400901 */  or         $t0, $t0, $t1
    /* 58AD4 800682D4 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 58AD8 800682D8 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 58ADC 800682DC 00000000 */  nop
    /* 58AE0 800682E0 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 58AE4 800682E4 0200A894 */  lhu        $t0, 0x2($a1)
    /* 58AE8 800682E8 0800A98C */  lw         $t1, 0x8($a1)
    /* 58AEC 800682EC 0E00AA84 */  lh         $t2, 0xE($a1)
    /* 58AF0 800682F0 004C0900 */  sll        $t1, $t1, 16
    /* 58AF4 800682F4 25400901 */  or         $t0, $t0, $t1
    /* 58AF8 800682F8 00480B48 */  mfc2       $t3, $9 /* handwritten instruction */
    /* 58AFC 800682FC 00500C48 */  mfc2       $t4, $10 /* handwritten instruction */
    /* 58B00 80068300 00580D48 */  mfc2       $t5, $11 /* handwritten instruction */
    /* 58B04 80068304 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 58B08 80068308 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 58B0C 8006830C 00000000 */  nop
    /* 58B10 80068310 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 58B14 80068314 0400A894 */  lhu        $t0, 0x4($a1)
    /* 58B18 80068318 0800A98C */  lw         $t1, 0x8($a1)
    /* 58B1C 8006831C 1000AA8C */  lw         $t2, 0x10($a1)
    /* 58B20 80068320 FFFF013C */  lui        $at, (0xFFFF0000 >> 16)
    /* 58B24 80068324 24482101 */  and        $t1, $t1, $at
    /* 58B28 80068328 25400901 */  or         $t0, $t0, $t1
    /* 58B2C 8006832C 00480E48 */  mfc2       $t6, $9 /* handwritten instruction */
    /* 58B30 80068330 00500F48 */  mfc2       $t7, $10 /* handwritten instruction */
    /* 58B34 80068334 00581848 */  mfc2       $t8, $11 /* handwritten instruction */
    /* 58B38 80068338 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 58B3C 8006833C 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 58B40 80068340 00000000 */  nop
    /* 58B44 80068344 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 58B48 80068348 FFFF6B31 */  andi       $t3, $t3, 0xFFFF
    /* 58B4C 8006834C 00740E00 */  sll        $t6, $t6, 16
    /* 58B50 80068350 2570CB01 */  or         $t6, $t6, $t3
    /* 58B54 80068354 0000CEAC */  sw         $t6, 0x0($a2)
    /* 58B58 80068358 FFFFAD31 */  andi       $t5, $t5, 0xFFFF
    /* 58B5C 8006835C 00C41800 */  sll        $t8, $t8, 16
    /* 58B60 80068360 25C00D03 */  or         $t8, $t8, $t5
    /* 58B64 80068364 0C00D8AC */  sw         $t8, 0xC($a2)
    /* 58B68 80068368 00480848 */  mfc2       $t0, $9 /* handwritten instruction */
    /* 58B6C 8006836C 00500948 */  mfc2       $t1, $10 /* handwritten instruction */
    /* 58B70 80068370 1000CBE8 */  swc2       $11, 0x10($a2)
    /* 58B74 80068374 1400AD94 */  lhu        $t5, 0x14($a1)
    /* 58B78 80068378 1800AE8C */  lw         $t6, 0x18($a1)
    /* 58B7C 8006837C 1C00AA8C */  lw         $t2, 0x1C($a1)
    /* 58B80 80068380 00740E00 */  sll        $t6, $t6, 16
    /* 58B84 80068384 2568AE01 */  or         $t5, $t5, $t6
    /* 58B88 80068388 00008D48 */  mtc2       $t5, $0 /* handwritten instruction */
    /* 58B8C 8006838C 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 58B90 80068390 00000000 */  nop
    /* 58B94 80068394 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 58B98 80068398 00640C00 */  sll        $t4, $t4, 16
    /* 58B9C 8006839C FFFF0831 */  andi       $t0, $t0, 0xFFFF
    /* 58BA0 800683A0 25400C01 */  or         $t0, $t0, $t4
    /* 58BA4 800683A4 0400C8AC */  sw         $t0, 0x4($a2)
    /* 58BA8 800683A8 FFFFEF31 */  andi       $t7, $t7, 0xFFFF
    /* 58BAC 800683AC 004C0900 */  sll        $t1, $t1, 16
    /* 58BB0 800683B0 25482F01 */  or         $t1, $t1, $t7
    /* 58BB4 800683B4 0800C9AC */  sw         $t1, 0x8($a2)
    /* 58BB8 800683B8 00C80848 */  mfc2       $t0, $25 /* handwritten instruction */
    /* 58BBC 800683BC 00D00948 */  mfc2       $t1, $26 /* handwritten instruction */
    /* 58BC0 800683C0 00D80A48 */  mfc2       $t2, $27 /* handwritten instruction */
    /* 58BC4 800683C4 14008B8C */  lw         $t3, 0x14($a0)
    /* 58BC8 800683C8 18008C8C */  lw         $t4, 0x18($a0)
    /* 58BCC 800683CC 1C008D8C */  lw         $t5, 0x1C($a0)
    /* 58BD0 800683D0 20400B01 */  add        $t0, $t0, $t3 /* handwritten instruction */
    /* 58BD4 800683D4 20482C01 */  add        $t1, $t1, $t4 /* handwritten instruction */
    /* 58BD8 800683D8 20504D01 */  add        $t2, $t2, $t5 /* handwritten instruction */
    /* 58BDC 800683DC 1400C8AC */  sw         $t0, 0x14($a2)
    /* 58BE0 800683E0 1800C9AC */  sw         $t1, 0x18($a2)
    /* 58BE4 800683E4 1C00CAAC */  sw         $t2, 0x1C($a2)
    /* 58BE8 800683E8 2110C000 */  addu       $v0, $a2, $zero
    /* 58BEC 800683EC 0800E003 */  jr         $ra
    /* 58BF0 800683F0 00000000 */   nop
endlabel CompMatrix

/* Handwritten function */
nonmatching MulMatrix0, 0x10C

glabel MulMatrix0
    /* 58BF4 800683F4 0000888C */  lw         $t0, 0x0($a0)
    /* 58BF8 800683F8 0400898C */  lw         $t1, 0x4($a0)
    /* 58BFC 800683FC 08008A8C */  lw         $t2, 0x8($a0)
    /* 58C00 80068400 0C008B8C */  lw         $t3, 0xC($a0)
    /* 58C04 80068404 10008C8C */  lw         $t4, 0x10($a0)
    /* 58C08 80068408 0000C848 */  ctc2       $t0, $0 /* handwritten instruction */
    /* 58C0C 8006840C 0008C948 */  ctc2       $t1, $1 /* handwritten instruction */
    /* 58C10 80068410 0010CA48 */  ctc2       $t2, $2 /* handwritten instruction */
    /* 58C14 80068414 0018CB48 */  ctc2       $t3, $3 /* handwritten instruction */
    /* 58C18 80068418 0020CC48 */  ctc2       $t4, $4 /* handwritten instruction */
    /* 58C1C 8006841C 0000A894 */  lhu        $t0, 0x0($a1)
    /* 58C20 80068420 0400A98C */  lw         $t1, 0x4($a1)
    /* 58C24 80068424 0C00AA8C */  lw         $t2, 0xC($a1)
    /* 58C28 80068428 FFFF013C */  lui        $at, (0xFFFF0000 >> 16)
    /* 58C2C 8006842C 24482101 */  and        $t1, $t1, $at
    /* 58C30 80068430 25400901 */  or         $t0, $t0, $t1
    /* 58C34 80068434 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 58C38 80068438 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 58C3C 8006843C 00000000 */  nop
    /* 58C40 80068440 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 58C44 80068444 0200A894 */  lhu        $t0, 0x2($a1)
    /* 58C48 80068448 0800A98C */  lw         $t1, 0x8($a1)
    /* 58C4C 8006844C 0E00AA84 */  lh         $t2, 0xE($a1)
    /* 58C50 80068450 004C0900 */  sll        $t1, $t1, 16
    /* 58C54 80068454 25400901 */  or         $t0, $t0, $t1
    /* 58C58 80068458 00480B48 */  mfc2       $t3, $9 /* handwritten instruction */
    /* 58C5C 8006845C 00500C48 */  mfc2       $t4, $10 /* handwritten instruction */
    /* 58C60 80068460 00580D48 */  mfc2       $t5, $11 /* handwritten instruction */
    /* 58C64 80068464 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 58C68 80068468 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 58C6C 8006846C 00000000 */  nop
    /* 58C70 80068470 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 58C74 80068474 0400A894 */  lhu        $t0, 0x4($a1)
    /* 58C78 80068478 0800A98C */  lw         $t1, 0x8($a1)
    /* 58C7C 8006847C 1000AA8C */  lw         $t2, 0x10($a1)
    /* 58C80 80068480 FFFF013C */  lui        $at, (0xFFFF0000 >> 16)
    /* 58C84 80068484 24482101 */  and        $t1, $t1, $at
    /* 58C88 80068488 25400901 */  or         $t0, $t0, $t1
    /* 58C8C 8006848C 00480E48 */  mfc2       $t6, $9 /* handwritten instruction */
    /* 58C90 80068490 00500F48 */  mfc2       $t7, $10 /* handwritten instruction */
    /* 58C94 80068494 00581848 */  mfc2       $t8, $11 /* handwritten instruction */
    /* 58C98 80068498 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 58C9C 8006849C 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 58CA0 800684A0 00000000 */  nop
    /* 58CA4 800684A4 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 58CA8 800684A8 FFFF6B31 */  andi       $t3, $t3, 0xFFFF
    /* 58CAC 800684AC 00740E00 */  sll        $t6, $t6, 16
    /* 58CB0 800684B0 2570CB01 */  or         $t6, $t6, $t3
    /* 58CB4 800684B4 0000CEAC */  sw         $t6, 0x0($a2)
    /* 58CB8 800684B8 FFFFAD31 */  andi       $t5, $t5, 0xFFFF
    /* 58CBC 800684BC 00C41800 */  sll        $t8, $t8, 16
    /* 58CC0 800684C0 25C00D03 */  or         $t8, $t8, $t5
    /* 58CC4 800684C4 0C00D8AC */  sw         $t8, 0xC($a2)
    /* 58CC8 800684C8 00480848 */  mfc2       $t0, $9 /* handwritten instruction */
    /* 58CCC 800684CC 00500948 */  mfc2       $t1, $10 /* handwritten instruction */
    /* 58CD0 800684D0 FFFF0831 */  andi       $t0, $t0, 0xFFFF
    /* 58CD4 800684D4 00640C00 */  sll        $t4, $t4, 16
    /* 58CD8 800684D8 25400C01 */  or         $t0, $t0, $t4
    /* 58CDC 800684DC 0400C8AC */  sw         $t0, 0x4($a2)
    /* 58CE0 800684E0 FFFFEF31 */  andi       $t7, $t7, 0xFFFF
    /* 58CE4 800684E4 004C0900 */  sll        $t1, $t1, 16
    /* 58CE8 800684E8 25482F01 */  or         $t1, $t1, $t7
    /* 58CEC 800684EC 0800C9AC */  sw         $t1, 0x8($a2)
    /* 58CF0 800684F0 1000CBE8 */  swc2       $11, 0x10($a2)
    /* 58CF4 800684F4 2110C000 */  addu       $v0, $a2, $zero
    /* 58CF8 800684F8 0800E003 */  jr         $ra
    /* 58CFC 800684FC 00000000 */   nop
endlabel MulMatrix0

/* Handwritten function */
nonmatching MulRotMatrix0, 0xE4

glabel MulRotMatrix0
    /* 58D00 80068500 00008894 */  lhu        $t0, 0x0($a0)
    /* 58D04 80068504 0400898C */  lw         $t1, 0x4($a0)
    /* 58D08 80068508 0C008A8C */  lw         $t2, 0xC($a0)
    /* 58D0C 8006850C FFFF013C */  lui        $at, (0xFFFF0000 >> 16)
    /* 58D10 80068510 24482101 */  and        $t1, $t1, $at
    /* 58D14 80068514 25400901 */  or         $t0, $t0, $t1
    /* 58D18 80068518 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 58D1C 8006851C 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 58D20 80068520 00000000 */  nop
    /* 58D24 80068524 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 58D28 80068528 02008894 */  lhu        $t0, 0x2($a0)
    /* 58D2C 8006852C 0800898C */  lw         $t1, 0x8($a0)
    /* 58D30 80068530 0E008A84 */  lh         $t2, 0xE($a0)
    /* 58D34 80068534 004C0900 */  sll        $t1, $t1, 16
    /* 58D38 80068538 25400901 */  or         $t0, $t0, $t1
    /* 58D3C 8006853C 00480B48 */  mfc2       $t3, $9 /* handwritten instruction */
    /* 58D40 80068540 00500C48 */  mfc2       $t4, $10 /* handwritten instruction */
    /* 58D44 80068544 00580D48 */  mfc2       $t5, $11 /* handwritten instruction */
    /* 58D48 80068548 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 58D4C 8006854C 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 58D50 80068550 00000000 */  nop
    /* 58D54 80068554 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 58D58 80068558 04008894 */  lhu        $t0, 0x4($a0)
    /* 58D5C 8006855C 0800898C */  lw         $t1, 0x8($a0)
    /* 58D60 80068560 10008A8C */  lw         $t2, 0x10($a0)
    /* 58D64 80068564 FFFF013C */  lui        $at, (0xFFFF0000 >> 16)
    /* 58D68 80068568 24482101 */  and        $t1, $t1, $at
    /* 58D6C 8006856C 25400901 */  or         $t0, $t0, $t1
    /* 58D70 80068570 00480E48 */  mfc2       $t6, $9 /* handwritten instruction */
    /* 58D74 80068574 00500F48 */  mfc2       $t7, $10 /* handwritten instruction */
    /* 58D78 80068578 00581848 */  mfc2       $t8, $11 /* handwritten instruction */
    /* 58D7C 8006857C 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 58D80 80068580 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 58D84 80068584 00000000 */  nop
    /* 58D88 80068588 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 58D8C 8006858C FFFF6B31 */  andi       $t3, $t3, 0xFFFF
    /* 58D90 80068590 00740E00 */  sll        $t6, $t6, 16
    /* 58D94 80068594 2570CB01 */  or         $t6, $t6, $t3
    /* 58D98 80068598 0000AEAC */  sw         $t6, 0x0($a1)
    /* 58D9C 8006859C FFFFAD31 */  andi       $t5, $t5, 0xFFFF
    /* 58DA0 800685A0 00C41800 */  sll        $t8, $t8, 16
    /* 58DA4 800685A4 25C00D03 */  or         $t8, $t8, $t5
    /* 58DA8 800685A8 0C00B8AC */  sw         $t8, 0xC($a1)
    /* 58DAC 800685AC 00480848 */  mfc2       $t0, $9 /* handwritten instruction */
    /* 58DB0 800685B0 00500948 */  mfc2       $t1, $10 /* handwritten instruction */
    /* 58DB4 800685B4 FFFF0831 */  andi       $t0, $t0, 0xFFFF
    /* 58DB8 800685B8 00640C00 */  sll        $t4, $t4, 16
    /* 58DBC 800685BC 25400C01 */  or         $t0, $t0, $t4
    /* 58DC0 800685C0 0400A8AC */  sw         $t0, 0x4($a1)
    /* 58DC4 800685C4 FFFFEF31 */  andi       $t7, $t7, 0xFFFF
    /* 58DC8 800685C8 004C0900 */  sll        $t1, $t1, 16
    /* 58DCC 800685CC 25482F01 */  or         $t1, $t1, $t7
    /* 58DD0 800685D0 0800A9AC */  sw         $t1, 0x8($a1)
    /* 58DD4 800685D4 1000ABE8 */  swc2       $11, 0x10($a1)
    /* 58DD8 800685D8 2110A000 */  addu       $v0, $a1, $zero
    /* 58DDC 800685DC 0800E003 */  jr         $ra
    /* 58DE0 800685E0 00000000 */   nop
endlabel MulRotMatrix0

/* Handwritten function */
nonmatching MulRotMatrix, 0xE8

glabel MulRotMatrix
    /* 58DE4 800685E4 0000888C */  lw         $t0, 0x0($a0)
    /* 58DE8 800685E8 0400898C */  lw         $t1, 0x4($a0)
    /* 58DEC 800685EC 0C008A8C */  lw         $t2, 0xC($a0)
    /* 58DF0 800685F0 FFFF0831 */  andi       $t0, $t0, 0xFFFF
    /* 58DF4 800685F4 FFFF013C */  lui        $at, (0xFFFF0000 >> 16)
    /* 58DF8 800685F8 24482101 */  and        $t1, $t1, $at
    /* 58DFC 800685FC 25400901 */  or         $t0, $t0, $t1
    /* 58E00 80068600 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 58E04 80068604 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 58E08 80068608 00000000 */  nop
    /* 58E0C 8006860C 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 58E10 80068610 02008894 */  lhu        $t0, 0x2($a0)
    /* 58E14 80068614 0800898C */  lw         $t1, 0x8($a0)
    /* 58E18 80068618 0E008A84 */  lh         $t2, 0xE($a0)
    /* 58E1C 8006861C 004C0900 */  sll        $t1, $t1, 16
    /* 58E20 80068620 25400901 */  or         $t0, $t0, $t1
    /* 58E24 80068624 00480B48 */  mfc2       $t3, $9 /* handwritten instruction */
    /* 58E28 80068628 00500C48 */  mfc2       $t4, $10 /* handwritten instruction */
    /* 58E2C 8006862C 00580D48 */  mfc2       $t5, $11 /* handwritten instruction */
    /* 58E30 80068630 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 58E34 80068634 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 58E38 80068638 00000000 */  nop
    /* 58E3C 8006863C 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 58E40 80068640 04008894 */  lhu        $t0, 0x4($a0)
    /* 58E44 80068644 0800898C */  lw         $t1, 0x8($a0)
    /* 58E48 80068648 10008A8C */  lw         $t2, 0x10($a0)
    /* 58E4C 8006864C FFFF013C */  lui        $at, (0xFFFF0000 >> 16)
    /* 58E50 80068650 24482101 */  and        $t1, $t1, $at
    /* 58E54 80068654 25400901 */  or         $t0, $t0, $t1
    /* 58E58 80068658 00480E48 */  mfc2       $t6, $9 /* handwritten instruction */
    /* 58E5C 8006865C 00500F48 */  mfc2       $t7, $10 /* handwritten instruction */
    /* 58E60 80068660 00581848 */  mfc2       $t8, $11 /* handwritten instruction */
    /* 58E64 80068664 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 58E68 80068668 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 58E6C 8006866C 00000000 */  nop
    /* 58E70 80068670 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 58E74 80068674 FFFF6B31 */  andi       $t3, $t3, 0xFFFF
    /* 58E78 80068678 00740E00 */  sll        $t6, $t6, 16
    /* 58E7C 8006867C 2570CB01 */  or         $t6, $t6, $t3
    /* 58E80 80068680 00008EAC */  sw         $t6, 0x0($a0)
    /* 58E84 80068684 FFFFAD31 */  andi       $t5, $t5, 0xFFFF
    /* 58E88 80068688 00C41800 */  sll        $t8, $t8, 16
    /* 58E8C 8006868C 25C00D03 */  or         $t8, $t8, $t5
    /* 58E90 80068690 0C0098AC */  sw         $t8, 0xC($a0)
    /* 58E94 80068694 00480848 */  mfc2       $t0, $9 /* handwritten instruction */
    /* 58E98 80068698 00500948 */  mfc2       $t1, $10 /* handwritten instruction */
    /* 58E9C 8006869C FFFF0831 */  andi       $t0, $t0, 0xFFFF
    /* 58EA0 800686A0 00640C00 */  sll        $t4, $t4, 16
    /* 58EA4 800686A4 25400C01 */  or         $t0, $t0, $t4
    /* 58EA8 800686A8 040088AC */  sw         $t0, 0x4($a0)
    /* 58EAC 800686AC FFFFEF31 */  andi       $t7, $t7, 0xFFFF
    /* 58EB0 800686B0 004C0900 */  sll        $t1, $t1, 16
    /* 58EB4 800686B4 25482F01 */  or         $t1, $t1, $t7
    /* 58EB8 800686B8 080089AC */  sw         $t1, 0x8($a0)
    /* 58EBC 800686BC 10008BE8 */  swc2       $11, 0x10($a0)
    /* 58EC0 800686C0 21108000 */  addu       $v0, $a0, $zero
    /* 58EC4 800686C4 0800E003 */  jr         $ra
    /* 58EC8 800686C8 00000000 */   nop
endlabel MulRotMatrix

/* Handwritten function */
nonmatching SetMulMatrix, 0x110

glabel SetMulMatrix
    /* 58ECC 800686CC 0000888C */  lw         $t0, 0x0($a0)
    /* 58ED0 800686D0 0400898C */  lw         $t1, 0x4($a0)
    /* 58ED4 800686D4 08008A8C */  lw         $t2, 0x8($a0)
    /* 58ED8 800686D8 0C008B8C */  lw         $t3, 0xC($a0)
    /* 58EDC 800686DC 10008C8C */  lw         $t4, 0x10($a0)
    /* 58EE0 800686E0 0000C848 */  ctc2       $t0, $0 /* handwritten instruction */
    /* 58EE4 800686E4 0008C948 */  ctc2       $t1, $1 /* handwritten instruction */
    /* 58EE8 800686E8 0010CA48 */  ctc2       $t2, $2 /* handwritten instruction */
    /* 58EEC 800686EC 0018CB48 */  ctc2       $t3, $3 /* handwritten instruction */
    /* 58EF0 800686F0 0020CC48 */  ctc2       $t4, $4 /* handwritten instruction */
    /* 58EF4 800686F4 0000A894 */  lhu        $t0, 0x0($a1)
    /* 58EF8 800686F8 0400A98C */  lw         $t1, 0x4($a1)
    /* 58EFC 800686FC 0C00AA8C */  lw         $t2, 0xC($a1)
    /* 58F00 80068700 FFFF013C */  lui        $at, (0xFFFF0000 >> 16)
    /* 58F04 80068704 24482101 */  and        $t1, $t1, $at
    /* 58F08 80068708 25400901 */  or         $t0, $t0, $t1
    /* 58F0C 8006870C 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 58F10 80068710 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 58F14 80068714 00000000 */  nop
    /* 58F18 80068718 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 58F1C 8006871C 0200A894 */  lhu        $t0, 0x2($a1)
    /* 58F20 80068720 0800A98C */  lw         $t1, 0x8($a1)
    /* 58F24 80068724 0E00AA84 */  lh         $t2, 0xE($a1)
    /* 58F28 80068728 004C0900 */  sll        $t1, $t1, 16
    /* 58F2C 8006872C 25400901 */  or         $t0, $t0, $t1
    /* 58F30 80068730 00480B48 */  mfc2       $t3, $9 /* handwritten instruction */
    /* 58F34 80068734 00500C48 */  mfc2       $t4, $10 /* handwritten instruction */
    /* 58F38 80068738 00580D48 */  mfc2       $t5, $11 /* handwritten instruction */
    /* 58F3C 8006873C 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 58F40 80068740 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 58F44 80068744 00000000 */  nop
    /* 58F48 80068748 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 58F4C 8006874C 0400A894 */  lhu        $t0, 0x4($a1)
    /* 58F50 80068750 0800A98C */  lw         $t1, 0x8($a1)
    /* 58F54 80068754 1000AA8C */  lw         $t2, 0x10($a1)
    /* 58F58 80068758 FFFF013C */  lui        $at, (0xFFFF0000 >> 16)
    /* 58F5C 8006875C 24482101 */  and        $t1, $t1, $at
    /* 58F60 80068760 25400901 */  or         $t0, $t0, $t1
    /* 58F64 80068764 00480E48 */  mfc2       $t6, $9 /* handwritten instruction */
    /* 58F68 80068768 00500F48 */  mfc2       $t7, $10 /* handwritten instruction */
    /* 58F6C 8006876C 00581848 */  mfc2       $t8, $11 /* handwritten instruction */
    /* 58F70 80068770 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 58F74 80068774 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 58F78 80068778 00000000 */  nop
    /* 58F7C 8006877C 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 58F80 80068780 FFFF6B31 */  andi       $t3, $t3, 0xFFFF
    /* 58F84 80068784 00740E00 */  sll        $t6, $t6, 16
    /* 58F88 80068788 2570CB01 */  or         $t6, $t6, $t3
    /* 58F8C 8006878C FFFFAD31 */  andi       $t5, $t5, 0xFFFF
    /* 58F90 80068790 00C41800 */  sll        $t8, $t8, 16
    /* 58F94 80068794 25C00D03 */  or         $t8, $t8, $t5
    /* 58F98 80068798 00480848 */  mfc2       $t0, $9 /* handwritten instruction */
    /* 58F9C 8006879C 00500948 */  mfc2       $t1, $10 /* handwritten instruction */
    /* 58FA0 800687A0 00580A48 */  mfc2       $t2, $11 /* handwritten instruction */
    /* 58FA4 800687A4 FFFF0831 */  andi       $t0, $t0, 0xFFFF
    /* 58FA8 800687A8 00640C00 */  sll        $t4, $t4, 16
    /* 58FAC 800687AC 25400C01 */  or         $t0, $t0, $t4
    /* 58FB0 800687B0 FFFFEF31 */  andi       $t7, $t7, 0xFFFF
    /* 58FB4 800687B4 004C0900 */  sll        $t1, $t1, 16
    /* 58FB8 800687B8 25482F01 */  or         $t1, $t1, $t7
    /* 58FBC 800687BC 0000CE48 */  ctc2       $t6, $0 /* handwritten instruction */
    /* 58FC0 800687C0 0008C848 */  ctc2       $t0, $1 /* handwritten instruction */
    /* 58FC4 800687C4 0010C948 */  ctc2       $t1, $2 /* handwritten instruction */
    /* 58FC8 800687C8 0018D848 */  ctc2       $t8, $3 /* handwritten instruction */
    /* 58FCC 800687CC 0020CA48 */  ctc2       $t2, $4 /* handwritten instruction */
    /* 58FD0 800687D0 21108000 */  addu       $v0, $a0, $zero
    /* 58FD4 800687D4 0800E003 */  jr         $ra
    /* 58FD8 800687D8 00000000 */   nop
endlabel SetMulMatrix

/* Handwritten function */
nonmatching ApplyMatrixLV, 0x160

glabel ApplyMatrixLV
    /* 58FDC 800687DC 0000888C */  lw         $t0, 0x0($a0)
    /* 58FE0 800687E0 0400898C */  lw         $t1, 0x4($a0)
    /* 58FE4 800687E4 08008A8C */  lw         $t2, 0x8($a0)
    /* 58FE8 800687E8 0C008B8C */  lw         $t3, 0xC($a0)
    /* 58FEC 800687EC 10008C8C */  lw         $t4, 0x10($a0)
    /* 58FF0 800687F0 0000C848 */  ctc2       $t0, $0 /* handwritten instruction */
    /* 58FF4 800687F4 0008C948 */  ctc2       $t1, $1 /* handwritten instruction */
    /* 58FF8 800687F8 0010CA48 */  ctc2       $t2, $2 /* handwritten instruction */
    /* 58FFC 800687FC 0018CB48 */  ctc2       $t3, $3 /* handwritten instruction */
    /* 59000 80068800 0020CC48 */  ctc2       $t4, $4 /* handwritten instruction */
    /* 59004 80068804 0000A88C */  lw         $t0, 0x0($a1)
    /* 59008 80068808 0400A98C */  lw         $t1, 0x4($a1)
    /* 5900C 8006880C 0800AA8C */  lw         $t2, 0x8($a1)
    /* 59010 80068810 08000105 */  bgez       $t0, .L80068834
    /* 59014 80068814 C35B0800 */   sra       $t3, $t0, 15
    /* 59018 80068818 23400800 */  negu       $t0, $t0
    /* 5901C 8006881C C35B0800 */  sra        $t3, $t0, 15
    /* 59020 80068820 FF7F0831 */  andi       $t0, $t0, 0x7FFF
    /* 59024 80068824 23580B00 */  negu       $t3, $t3
    /* 59028 80068828 03000010 */  b          .L80068838
    /* 5902C 8006882C 23400800 */   negu      $t0, $t0
    /* 59030 80068830 C35B0800 */  sra        $t3, $t0, 15
  .L80068834:
    /* 59034 80068834 FF7F0831 */  andi       $t0, $t0, 0x7FFF
  .L80068838:
    /* 59038 80068838 08002105 */  bgez       $t1, .L8006885C
    /* 5903C 8006883C C3630900 */   sra       $t4, $t1, 15
    /* 59040 80068840 23480900 */  negu       $t1, $t1
    /* 59044 80068844 C3630900 */  sra        $t4, $t1, 15
    /* 59048 80068848 FF7F2931 */  andi       $t1, $t1, 0x7FFF
    /* 5904C 8006884C 23600C00 */  negu       $t4, $t4
    /* 59050 80068850 03000010 */  b          .L80068860
    /* 59054 80068854 23480900 */   negu      $t1, $t1
    /* 59058 80068858 C3630900 */  sra        $t4, $t1, 15
  .L8006885C:
    /* 5905C 8006885C FF7F2931 */  andi       $t1, $t1, 0x7FFF
  .L80068860:
    /* 59060 80068860 08004105 */  bgez       $t2, .L80068884
    /* 59064 80068864 C36B0A00 */   sra       $t5, $t2, 15
    /* 59068 80068868 23500A00 */  negu       $t2, $t2
    /* 5906C 8006886C C36B0A00 */  sra        $t5, $t2, 15
    /* 59070 80068870 FF7F4A31 */  andi       $t2, $t2, 0x7FFF
    /* 59074 80068874 23680D00 */  negu       $t5, $t5
    /* 59078 80068878 03000010 */  b          .L80068888
    /* 5907C 8006887C 23500A00 */   negu      $t2, $t2
    /* 59080 80068880 C36B0A00 */  sra        $t5, $t2, 15
  .L80068884:
    /* 59084 80068884 FF7F4A31 */  andi       $t2, $t2, 0x7FFF
  .L80068888:
    /* 59088 80068888 00488B48 */  mtc2       $t3, $9 /* handwritten instruction */
    /* 5908C 8006888C 00508C48 */  mtc2       $t4, $10 /* handwritten instruction */
    /* 59090 80068890 00588D48 */  mtc2       $t5, $11 /* handwritten instruction */
    /* 59094 80068894 00000000 */  nop
    /* 59098 80068898 12E0414A */  mvmva      0, 0, 3, 3, 0
    /* 5909C 8006889C 00C80B48 */  mfc2       $t3, $25 /* handwritten instruction */
    /* 590A0 800688A0 00D00C48 */  mfc2       $t4, $26 /* handwritten instruction */
    /* 590A4 800688A4 00D80D48 */  mfc2       $t5, $27 /* handwritten instruction */
    /* 590A8 800688A8 00488848 */  mtc2       $t0, $9 /* handwritten instruction */
    /* 590AC 800688AC 00508948 */  mtc2       $t1, $10 /* handwritten instruction */
    /* 590B0 800688B0 00588A48 */  mtc2       $t2, $11 /* handwritten instruction */
    /* 590B4 800688B4 00000000 */  nop
    /* 590B8 800688B8 12E0494A */  mvmva      1, 0, 3, 3, 0
    /* 590BC 800688BC 05006105 */  bgez       $t3, .L800688D4
    /* 590C0 800688C0 00000000 */   nop
    /* 590C4 800688C4 23580B00 */  negu       $t3, $t3
    /* 590C8 800688C8 C0580B00 */  sll        $t3, $t3, 3
    /* 590CC 800688CC 02000010 */  b          .L800688D8
    /* 590D0 800688D0 23580B00 */   negu      $t3, $t3
  .L800688D4:
    /* 590D4 800688D4 C0580B00 */  sll        $t3, $t3, 3
  .L800688D8:
    /* 590D8 800688D8 05008105 */  bgez       $t4, .L800688F0
    /* 590DC 800688DC 00000000 */   nop
    /* 590E0 800688E0 23600C00 */  negu       $t4, $t4
    /* 590E4 800688E4 C0600C00 */  sll        $t4, $t4, 3
    /* 590E8 800688E8 02000010 */  b          .L800688F4
    /* 590EC 800688EC 23600C00 */   negu      $t4, $t4
  .L800688F0:
    /* 590F0 800688F0 C0600C00 */  sll        $t4, $t4, 3
  .L800688F4:
    /* 590F4 800688F4 0500A105 */  bgez       $t5, .L8006890C
    /* 590F8 800688F8 00000000 */   nop
    /* 590FC 800688FC 23680D00 */  negu       $t5, $t5
    /* 59100 80068900 C0680D00 */  sll        $t5, $t5, 3
    /* 59104 80068904 02000010 */  b          .L80068910
    /* 59108 80068908 23680D00 */   negu      $t5, $t5
  .L8006890C:
    /* 5910C 8006890C C0680D00 */  sll        $t5, $t5, 3
  .L80068910:
    /* 59110 80068910 00C80848 */  mfc2       $t0, $25 /* handwritten instruction */
    /* 59114 80068914 00D00948 */  mfc2       $t1, $26 /* handwritten instruction */
    /* 59118 80068918 00D80A48 */  mfc2       $t2, $27 /* handwritten instruction */
    /* 5911C 8006891C 21400B01 */  addu       $t0, $t0, $t3
    /* 59120 80068920 21482C01 */  addu       $t1, $t1, $t4
    /* 59124 80068924 21504D01 */  addu       $t2, $t2, $t5
    /* 59128 80068928 0000C8AC */  sw         $t0, 0x0($a2)
    /* 5912C 8006892C 0400C9AC */  sw         $t1, 0x4($a2)
    /* 59130 80068930 0800CAAC */  sw         $t2, 0x8($a2)
    /* 59134 80068934 0800E003 */  jr         $ra
    /* 59138 80068938 2110C000 */   addu      $v0, $a2, $zero
endlabel ApplyMatrixLV

/* Handwritten function */
nonmatching TransformCollisionVector, 0x30

glabel TransformCollisionVector
    /* 5913C 8006893C 0000888C */  lw         $t0, 0x0($a0)
    /* 59140 80068940 0400898C */  lw         $t1, 0x4($a0)
    /* 59144 80068944 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 59148 80068948 00088948 */  mtc2       $t1, $1 /* handwritten instruction */
    /* 5914C 8006894C 00000000 */  nop
    /* 59150 80068950 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 59154 80068954 0000A9E8 */  swc2       $9, 0x0($a1)
    /* 59158 80068958 0400AAE8 */  swc2       $10, 0x4($a1)
    /* 5915C 8006895C 0800ABE8 */  swc2       $11, 0x8($a1)
    /* 59160 80068960 2110C000 */  addu       $v0, $a2, $zero
    /* 59164 80068964 0800E003 */  jr         $ra
    /* 59168 80068968 00000000 */   nop
endlabel TransformCollisionVector

nonmatching func_8006896C, 0x124

glabel func_8006896C
    /* 5916C 8006896C 0000888C */  lw         $t0, 0x0($a0)
    /* 59170 80068970 0000AB8C */  lw         $t3, 0x0($a1)
    /* 59174 80068974 FFFF0931 */  andi       $t1, $t0, 0xFFFF
    /* 59178 80068978 004C0900 */  sll        $t1, $t1, 16
    /* 5917C 8006897C 034C0900 */  sra        $t1, $t1, 16
    /* 59180 80068980 19002B01 */  multu      $t1, $t3
    /* 59184 80068984 03540800 */  sra        $t2, $t0, 16
    /* 59188 80068988 0400AC8C */  lw         $t4, 0x4($a1)
    /* 5918C 8006898C 0800AD8C */  lw         $t5, 0x8($a1)
    /* 59190 80068990 0400888C */  lw         $t0, 0x4($a0)
    /* 59194 80068994 21108000 */  addu       $v0, $a0, $zero
    /* 59198 80068998 12480000 */  mflo       $t1
    /* 5919C 8006899C 034B0900 */  sra        $t1, $t1, 12
    /* 591A0 800689A0 FFFF2931 */  andi       $t1, $t1, 0xFFFF
    /* 591A4 800689A4 19004B01 */  multu      $t2, $t3
    /* 591A8 800689A8 12500000 */  mflo       $t2
    /* 591AC 800689AC 03530A00 */  sra        $t2, $t2, 12
    /* 591B0 800689B0 00540A00 */  sll        $t2, $t2, 16
    /* 591B4 800689B4 25482A01 */  or         $t1, $t1, $t2
    /* 591B8 800689B8 000089AC */  sw         $t1, 0x0($a0)
    /* 591BC 800689BC FFFF0931 */  andi       $t1, $t0, 0xFFFF
    /* 591C0 800689C0 004C0900 */  sll        $t1, $t1, 16
    /* 591C4 800689C4 034C0900 */  sra        $t1, $t1, 16
    /* 591C8 800689C8 19002B01 */  multu      $t1, $t3
    /* 591CC 800689CC 03540800 */  sra        $t2, $t0, 16
    /* 591D0 800689D0 0800888C */  lw         $t0, 0x8($a0)
    /* 591D4 800689D4 12480000 */  mflo       $t1
    /* 591D8 800689D8 034B0900 */  sra        $t1, $t1, 12
    /* 591DC 800689DC FFFF2931 */  andi       $t1, $t1, 0xFFFF
    /* 591E0 800689E0 19004C01 */  multu      $t2, $t4
    /* 591E4 800689E4 12500000 */  mflo       $t2
    /* 591E8 800689E8 03530A00 */  sra        $t2, $t2, 12
    /* 591EC 800689EC 00540A00 */  sll        $t2, $t2, 16
    /* 591F0 800689F0 25482A01 */  or         $t1, $t1, $t2
    /* 591F4 800689F4 040089AC */  sw         $t1, 0x4($a0)
    /* 591F8 800689F8 FFFF0931 */  andi       $t1, $t0, 0xFFFF
    /* 591FC 800689FC 004C0900 */  sll        $t1, $t1, 16
    /* 59200 80068A00 034C0900 */  sra        $t1, $t1, 16
    /* 59204 80068A04 19002C01 */  multu      $t1, $t4
    /* 59208 80068A08 03540800 */  sra        $t2, $t0, 16
    /* 5920C 80068A0C 0C00888C */  lw         $t0, 0xC($a0)
    /* 59210 80068A10 12480000 */  mflo       $t1
    /* 59214 80068A14 034B0900 */  sra        $t1, $t1, 12
    /* 59218 80068A18 FFFF2931 */  andi       $t1, $t1, 0xFFFF
    /* 5921C 80068A1C 19004C01 */  multu      $t2, $t4
    /* 59220 80068A20 12500000 */  mflo       $t2
    /* 59224 80068A24 03530A00 */  sra        $t2, $t2, 12
    /* 59228 80068A28 00540A00 */  sll        $t2, $t2, 16
    /* 5922C 80068A2C 25482A01 */  or         $t1, $t1, $t2
    /* 59230 80068A30 080089AC */  sw         $t1, 0x8($a0)
    /* 59234 80068A34 FFFF0931 */  andi       $t1, $t0, 0xFFFF
    /* 59238 80068A38 004C0900 */  sll        $t1, $t1, 16
    /* 5923C 80068A3C 034C0900 */  sra        $t1, $t1, 16
    /* 59240 80068A40 19002D01 */  multu      $t1, $t5
    /* 59244 80068A44 03540800 */  sra        $t2, $t0, 16
    /* 59248 80068A48 1000888C */  lw         $t0, 0x10($a0)
    /* 5924C 80068A4C 12480000 */  mflo       $t1
    /* 59250 80068A50 034B0900 */  sra        $t1, $t1, 12
    /* 59254 80068A54 FFFF2931 */  andi       $t1, $t1, 0xFFFF
    /* 59258 80068A58 19004D01 */  multu      $t2, $t5
    /* 5925C 80068A5C 12500000 */  mflo       $t2
    /* 59260 80068A60 03530A00 */  sra        $t2, $t2, 12
    /* 59264 80068A64 00540A00 */  sll        $t2, $t2, 16
    /* 59268 80068A68 25482A01 */  or         $t1, $t1, $t2
    /* 5926C 80068A6C 0C0089AC */  sw         $t1, 0xC($a0)
    /* 59270 80068A70 FFFF0931 */  andi       $t1, $t0, 0xFFFF
    /* 59274 80068A74 004C0900 */  sll        $t1, $t1, 16
    /* 59278 80068A78 034C0900 */  sra        $t1, $t1, 16
    /* 5927C 80068A7C 19002D01 */  multu      $t1, $t5
    /* 59280 80068A80 12480000 */  mflo       $t1
    /* 59284 80068A84 034B0900 */  sra        $t1, $t1, 12
    /* 59288 80068A88 0800E003 */  jr         $ra
    /* 5928C 80068A8C 100089AC */   sw        $t1, 0x10($a0)
endlabel func_8006896C

/* Handwritten function */
nonmatching PushMatrix, 0xA0

glabel PushMatrix
    /* 59290 80068A90 09800E3C */  lui        $t6, %hi(D_80094350)
    /* 59294 80068A94 5043CE8D */  lw         $t6, %lo(D_80094350)($t6)
    /* 59298 80068A98 00000000 */  nop
    /* 5929C 80068A9C 8002C129 */  slti       $at, $t6, 0x280
    /* 592A0 80068AA0 0A002014 */  bnez       $at, .L80068ACC
    /* 592A4 80068AA4 0980013C */   lui       $at, %hi(D_80094344)
    /* 592A8 80068AA8 44433FAC */  sw         $ra, %lo(D_80094344)($at)
    /* 592AC 80068AAC 0980043C */  lui        $a0, %hi(D_800945D4)
    /* 592B0 80068AB0 6F59000C */  jal        printf
    /* 592B4 80068AB4 D4458424 */   addiu     $a0, $a0, %lo(D_800945D4)
    /* 592B8 80068AB8 09801F3C */  lui        $ra, %hi(D_80094344)
    /* 592BC 80068ABC 4443FF8F */  lw         $ra, %lo(D_80094344)($ra)
    /* 592C0 80068AC0 00000000 */  nop
    /* 592C4 80068AC4 0800E003 */  jr         $ra
    /* 592C8 80068AC8 00000000 */   nop
  .L80068ACC:
    /* 592CC 80068ACC 09800F3C */  lui        $t7, %hi(D_80094354)
    /* 592D0 80068AD0 2178EE01 */  addu       $t7, $t7, $t6
    /* 592D4 80068AD4 5443EF25 */  addiu      $t7, $t7, %lo(D_80094354)
    /* 592D8 80068AD8 00004848 */  cfc2       $t0, $0 /* handwritten instruction */
    /* 592DC 80068ADC 00084948 */  cfc2       $t1, $1 /* handwritten instruction */
    /* 592E0 80068AE0 0000E8AD */  sw         $t0, 0x0($t7)
    /* 592E4 80068AE4 0400E9AD */  sw         $t1, 0x4($t7)
    /* 592E8 80068AE8 00104848 */  cfc2       $t0, $2 /* handwritten instruction */
    /* 592EC 80068AEC 00184948 */  cfc2       $t1, $3 /* handwritten instruction */
    /* 592F0 80068AF0 0800E8AD */  sw         $t0, 0x8($t7)
    /* 592F4 80068AF4 0C00E9AD */  sw         $t1, 0xC($t7)
    /* 592F8 80068AF8 00204848 */  cfc2       $t0, $4 /* handwritten instruction */
    /* 592FC 80068AFC 00000000 */  nop
    /* 59300 80068B00 1000E8AD */  sw         $t0, 0x10($t7)
    /* 59304 80068B04 00284848 */  cfc2       $t0, $5 /* handwritten instruction */
    /* 59308 80068B08 00304948 */  cfc2       $t1, $6 /* handwritten instruction */
    /* 5930C 80068B0C 00384A48 */  cfc2       $t2, $7 /* handwritten instruction */
    /* 59310 80068B10 1400E8AD */  sw         $t0, 0x14($t7)
    /* 59314 80068B14 1800E9AD */  sw         $t1, 0x18($t7)
    /* 59318 80068B18 1C00EAAD */  sw         $t2, 0x1C($t7)
    /* 5931C 80068B1C 2000CE21 */  addi       $t6, $t6, 0x20 /* handwritten instruction */
    /* 59320 80068B20 0980013C */  lui        $at, %hi(D_80094350)
    /* 59324 80068B24 50432EAC */  sw         $t6, %lo(D_80094350)($at)
    /* 59328 80068B28 0800E003 */  jr         $ra
    /* 5932C 80068B2C 00000000 */   nop
endlabel PushMatrix

/* Handwritten function */
nonmatching PopMatrix, 0xA0

glabel PopMatrix
    /* 59330 80068B30 09800E3C */  lui        $t6, %hi(D_80094350)
    /* 59334 80068B34 5043CE8D */  lw         $t6, %lo(D_80094350)($t6)
    /* 59338 80068B38 00000000 */  nop
    /* 5933C 80068B3C 0A00C01D */  bgtz       $t6, .L80068B68
    /* 59340 80068B40 0980013C */   lui       $at, %hi(D_80094344)
    /* 59344 80068B44 44433FAC */  sw         $ra, %lo(D_80094344)($at)
    /* 59348 80068B48 0980043C */  lui        $a0, %hi(D_80094605)
    /* 5934C 80068B4C 6F59000C */  jal        printf
    /* 59350 80068B50 05468424 */   addiu     $a0, $a0, %lo(D_80094605)
    /* 59354 80068B54 09801F3C */  lui        $ra, %hi(D_80094344)
    /* 59358 80068B58 4443FF8F */  lw         $ra, %lo(D_80094344)($ra)
    /* 5935C 80068B5C 00000000 */  nop
    /* 59360 80068B60 0800E003 */  jr         $ra
    /* 59364 80068B64 00000000 */   nop
  .L80068B68:
    /* 59368 80068B68 E0FFCE21 */  addi       $t6, $t6, -0x20 /* handwritten instruction */
    /* 5936C 80068B6C 0980013C */  lui        $at, %hi(D_80094350)
    /* 59370 80068B70 50432EAC */  sw         $t6, %lo(D_80094350)($at)
    /* 59374 80068B74 09800F3C */  lui        $t7, %hi(D_80094354)
    /* 59378 80068B78 2178EE01 */  addu       $t7, $t7, $t6
    /* 5937C 80068B7C 5443EF25 */  addiu      $t7, $t7, %lo(D_80094354)
    /* 59380 80068B80 0000E88D */  lw         $t0, 0x0($t7)
    /* 59384 80068B84 0400E98D */  lw         $t1, 0x4($t7)
    /* 59388 80068B88 0000C848 */  ctc2       $t0, $0 /* handwritten instruction */
    /* 5938C 80068B8C 0008C948 */  ctc2       $t1, $1 /* handwritten instruction */
    /* 59390 80068B90 0800E88D */  lw         $t0, 0x8($t7)
    /* 59394 80068B94 0C00E98D */  lw         $t1, 0xC($t7)
    /* 59398 80068B98 0010C848 */  ctc2       $t0, $2 /* handwritten instruction */
    /* 5939C 80068B9C 0018C948 */  ctc2       $t1, $3 /* handwritten instruction */
    /* 593A0 80068BA0 1000E88D */  lw         $t0, 0x10($t7)
    /* 593A4 80068BA4 00000000 */  nop
    /* 593A8 80068BA8 0020C848 */  ctc2       $t0, $4 /* handwritten instruction */
    /* 593AC 80068BAC 00000000 */  nop
    /* 593B0 80068BB0 1400E88D */  lw         $t0, 0x14($t7)
    /* 593B4 80068BB4 1800E98D */  lw         $t1, 0x18($t7)
    /* 593B8 80068BB8 1C00EA8D */  lw         $t2, 0x1C($t7)
    /* 593BC 80068BBC 0028C848 */  ctc2       $t0, $5 /* handwritten instruction */
    /* 593C0 80068BC0 0030C948 */  ctc2       $t1, $6 /* handwritten instruction */
    /* 593C4 80068BC4 0038CA48 */  ctc2       $t2, $7 /* handwritten instruction */
    /* 593C8 80068BC8 0800E003 */  jr         $ra
    /* 593CC 80068BCC 00000000 */   nop
endlabel PopMatrix

/* Handwritten function */
nonmatching ReadRotMatrix, 0x48

glabel ReadRotMatrix
    /* 593D0 80068BD0 00004848 */  cfc2       $t0, $0 /* handwritten instruction */
    /* 593D4 80068BD4 00084948 */  cfc2       $t1, $1 /* handwritten instruction */
    /* 593D8 80068BD8 00104A48 */  cfc2       $t2, $2 /* handwritten instruction */
    /* 593DC 80068BDC 00184B48 */  cfc2       $t3, $3 /* handwritten instruction */
    /* 593E0 80068BE0 00204C48 */  cfc2       $t4, $4 /* handwritten instruction */
    /* 593E4 80068BE4 000088AC */  sw         $t0, 0x0($a0)
    /* 593E8 80068BE8 040089AC */  sw         $t1, 0x4($a0)
    /* 593EC 80068BEC 08008AAC */  sw         $t2, 0x8($a0)
    /* 593F0 80068BF0 0C008BAC */  sw         $t3, 0xC($a0)
    /* 593F4 80068BF4 10008CAC */  sw         $t4, 0x10($a0)
    /* 593F8 80068BF8 00284848 */  cfc2       $t0, $5 /* handwritten instruction */
    /* 593FC 80068BFC 00304948 */  cfc2       $t1, $6 /* handwritten instruction */
    /* 59400 80068C00 00384A48 */  cfc2       $t2, $7 /* handwritten instruction */
    /* 59404 80068C04 140088AC */  sw         $t0, 0x14($a0)
    /* 59408 80068C08 180089AC */  sw         $t1, 0x18($a0)
    /* 5940C 80068C0C 1C008AAC */  sw         $t2, 0x1C($a0)
    /* 59410 80068C10 0800E003 */  jr         $ra
    /* 59414 80068C14 00000000 */   nop
endlabel ReadRotMatrix

/* Handwritten function */
nonmatching ReadLightMatrix, 0x48

glabel ReadLightMatrix
    /* 59418 80068C18 00404848 */  cfc2       $t0, $8 /* handwritten instruction */
    /* 5941C 80068C1C 00484948 */  cfc2       $t1, $9 /* handwritten instruction */
    /* 59420 80068C20 00504A48 */  cfc2       $t2, $10 /* handwritten instruction */
    /* 59424 80068C24 00584B48 */  cfc2       $t3, $11 /* handwritten instruction */
    /* 59428 80068C28 00604C48 */  cfc2       $t4, $12 /* handwritten instruction */
    /* 5942C 80068C2C 000088AC */  sw         $t0, 0x0($a0)
    /* 59430 80068C30 040089AC */  sw         $t1, 0x4($a0)
    /* 59434 80068C34 08008AAC */  sw         $t2, 0x8($a0)
    /* 59438 80068C38 0C008BAC */  sw         $t3, 0xC($a0)
    /* 5943C 80068C3C 10008CAC */  sw         $t4, 0x10($a0)
    /* 59440 80068C40 00684848 */  cfc2       $t0, $13 /* handwritten instruction */
    /* 59444 80068C44 00704948 */  cfc2       $t1, $14 /* handwritten instruction */
    /* 59448 80068C48 00784A48 */  cfc2       $t2, $15 /* handwritten instruction */
    /* 5944C 80068C4C 140088AC */  sw         $t0, 0x14($a0)
    /* 59450 80068C50 180089AC */  sw         $t1, 0x18($a0)
    /* 59454 80068C54 1C008AAC */  sw         $t2, 0x1C($a0)
    /* 59458 80068C58 0800E003 */  jr         $ra
    /* 5945C 80068C5C 00000000 */   nop
endlabel ReadLightMatrix

/* Handwritten function */
nonmatching ReadColorMatrix, 0x48

glabel ReadColorMatrix
    /* 59460 80068C60 00804848 */  cfc2       $t0, $16 /* handwritten instruction */
    /* 59464 80068C64 00884948 */  cfc2       $t1, $17 /* handwritten instruction */
    /* 59468 80068C68 00904A48 */  cfc2       $t2, $18 /* handwritten instruction */
    /* 5946C 80068C6C 00984B48 */  cfc2       $t3, $19 /* handwritten instruction */
    /* 59470 80068C70 00A04C48 */  cfc2       $t4, $20 /* handwritten instruction */
    /* 59474 80068C74 000088AC */  sw         $t0, 0x0($a0)
    /* 59478 80068C78 040089AC */  sw         $t1, 0x4($a0)
    /* 5947C 80068C7C 08008AAC */  sw         $t2, 0x8($a0)
    /* 59480 80068C80 0C008BAC */  sw         $t3, 0xC($a0)
    /* 59484 80068C84 10008CAC */  sw         $t4, 0x10($a0)
    /* 59488 80068C88 00A84848 */  cfc2       $t0, $21 /* handwritten instruction */
    /* 5948C 80068C8C 00B04948 */  cfc2       $t1, $22 /* handwritten instruction */
    /* 59490 80068C90 00B84A48 */  cfc2       $t2, $23 /* handwritten instruction */
    /* 59494 80068C94 140088AC */  sw         $t0, 0x14($a0)
    /* 59498 80068C98 180089AC */  sw         $t1, 0x18($a0)
    /* 5949C 80068C9C 1C008AAC */  sw         $t2, 0x1C($a0)
    /* 594A0 80068CA0 0800E003 */  jr         $ra
    /* 594A4 80068CA4 00000000 */   nop
endlabel ReadColorMatrix
    /* 594A8 80068CA8 00000000 */  nop
    /* 594AC 80068CAC 00000000 */  nop
    /* 594B0 80068CB0 00000000 */  nop

/* Handwritten function */
nonmatching MulMatrix, 0x10C

glabel MulMatrix
    /* 594B4 80068CB4 0000888C */  lw         $t0, 0x0($a0)
    /* 594B8 80068CB8 0400898C */  lw         $t1, 0x4($a0)
    /* 594BC 80068CBC 08008A8C */  lw         $t2, 0x8($a0)
    /* 594C0 80068CC0 0C008B8C */  lw         $t3, 0xC($a0)
    /* 594C4 80068CC4 10008C8C */  lw         $t4, 0x10($a0)
    /* 594C8 80068CC8 0000C848 */  ctc2       $t0, $0 /* handwritten instruction */
    /* 594CC 80068CCC 0008C948 */  ctc2       $t1, $1 /* handwritten instruction */
    /* 594D0 80068CD0 0010CA48 */  ctc2       $t2, $2 /* handwritten instruction */
    /* 594D4 80068CD4 0018CB48 */  ctc2       $t3, $3 /* handwritten instruction */
    /* 594D8 80068CD8 0020CC48 */  ctc2       $t4, $4 /* handwritten instruction */
    /* 594DC 80068CDC 0000A894 */  lhu        $t0, 0x0($a1)
    /* 594E0 80068CE0 0400A98C */  lw         $t1, 0x4($a1)
    /* 594E4 80068CE4 0C00AA8C */  lw         $t2, 0xC($a1)
    /* 594E8 80068CE8 FFFF013C */  lui        $at, (0xFFFF0000 >> 16)
    /* 594EC 80068CEC 24482101 */  and        $t1, $t1, $at
    /* 594F0 80068CF0 25400901 */  or         $t0, $t0, $t1
    /* 594F4 80068CF4 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 594F8 80068CF8 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 594FC 80068CFC 00000000 */  nop
    /* 59500 80068D00 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 59504 80068D04 0200A894 */  lhu        $t0, 0x2($a1)
    /* 59508 80068D08 0800A98C */  lw         $t1, 0x8($a1)
    /* 5950C 80068D0C 0E00AA84 */  lh         $t2, 0xE($a1)
    /* 59510 80068D10 004C0900 */  sll        $t1, $t1, 16
    /* 59514 80068D14 25400901 */  or         $t0, $t0, $t1
    /* 59518 80068D18 00480B48 */  mfc2       $t3, $9 /* handwritten instruction */
    /* 5951C 80068D1C 00500C48 */  mfc2       $t4, $10 /* handwritten instruction */
    /* 59520 80068D20 00580D48 */  mfc2       $t5, $11 /* handwritten instruction */
    /* 59524 80068D24 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 59528 80068D28 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 5952C 80068D2C 00000000 */  nop
    /* 59530 80068D30 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 59534 80068D34 0400A894 */  lhu        $t0, 0x4($a1)
    /* 59538 80068D38 0800A98C */  lw         $t1, 0x8($a1)
    /* 5953C 80068D3C 1000AA8C */  lw         $t2, 0x10($a1)
    /* 59540 80068D40 FFFF013C */  lui        $at, (0xFFFF0000 >> 16)
    /* 59544 80068D44 24482101 */  and        $t1, $t1, $at
    /* 59548 80068D48 25400901 */  or         $t0, $t0, $t1
    /* 5954C 80068D4C 00480E48 */  mfc2       $t6, $9 /* handwritten instruction */
    /* 59550 80068D50 00500F48 */  mfc2       $t7, $10 /* handwritten instruction */
    /* 59554 80068D54 00581848 */  mfc2       $t8, $11 /* handwritten instruction */
    /* 59558 80068D58 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 5955C 80068D5C 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 59560 80068D60 00000000 */  nop
    /* 59564 80068D64 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 59568 80068D68 FFFF6B31 */  andi       $t3, $t3, 0xFFFF
    /* 5956C 80068D6C 00740E00 */  sll        $t6, $t6, 16
    /* 59570 80068D70 2570CB01 */  or         $t6, $t6, $t3
    /* 59574 80068D74 00008EAC */  sw         $t6, 0x0($a0)
    /* 59578 80068D78 FFFFAD31 */  andi       $t5, $t5, 0xFFFF
    /* 5957C 80068D7C 00C41800 */  sll        $t8, $t8, 16
    /* 59580 80068D80 25C00D03 */  or         $t8, $t8, $t5
    /* 59584 80068D84 0C0098AC */  sw         $t8, 0xC($a0)
    /* 59588 80068D88 00480848 */  mfc2       $t0, $9 /* handwritten instruction */
    /* 5958C 80068D8C 00500948 */  mfc2       $t1, $10 /* handwritten instruction */
    /* 59590 80068D90 FFFF0831 */  andi       $t0, $t0, 0xFFFF
    /* 59594 80068D94 00640C00 */  sll        $t4, $t4, 16
    /* 59598 80068D98 25400C01 */  or         $t0, $t0, $t4
    /* 5959C 80068D9C 040088AC */  sw         $t0, 0x4($a0)
    /* 595A0 80068DA0 FFFFEF31 */  andi       $t7, $t7, 0xFFFF
    /* 595A4 80068DA4 004C0900 */  sll        $t1, $t1, 16
    /* 595A8 80068DA8 25482F01 */  or         $t1, $t1, $t7
    /* 595AC 80068DAC 080089AC */  sw         $t1, 0x8($a0)
    /* 595B0 80068DB0 10008BE8 */  swc2       $11, 0x10($a0)
    /* 595B4 80068DB4 21108000 */  addu       $v0, $a0, $zero
    /* 595B8 80068DB8 0800E003 */  jr         $ra
    /* 595BC 80068DBC 00000000 */   nop
endlabel MulMatrix
    /* 595C0 80068DC0 00000000 */  nop

/* Handwritten function */
nonmatching MulMatrix2, 0x10C

glabel MulMatrix2
    /* 595C4 80068DC4 0000888C */  lw         $t0, 0x0($a0)
    /* 595C8 80068DC8 0400898C */  lw         $t1, 0x4($a0)
    /* 595CC 80068DCC 08008A8C */  lw         $t2, 0x8($a0)
    /* 595D0 80068DD0 0C008B8C */  lw         $t3, 0xC($a0)
    /* 595D4 80068DD4 10008C8C */  lw         $t4, 0x10($a0)
    /* 595D8 80068DD8 0000C848 */  ctc2       $t0, $0 /* handwritten instruction */
    /* 595DC 80068DDC 0008C948 */  ctc2       $t1, $1 /* handwritten instruction */
    /* 595E0 80068DE0 0010CA48 */  ctc2       $t2, $2 /* handwritten instruction */
    /* 595E4 80068DE4 0018CB48 */  ctc2       $t3, $3 /* handwritten instruction */
    /* 595E8 80068DE8 0020CC48 */  ctc2       $t4, $4 /* handwritten instruction */
    /* 595EC 80068DEC 0000A894 */  lhu        $t0, 0x0($a1)
    /* 595F0 80068DF0 0400A98C */  lw         $t1, 0x4($a1)
    /* 595F4 80068DF4 0C00AA8C */  lw         $t2, 0xC($a1)
    /* 595F8 80068DF8 FFFF013C */  lui        $at, (0xFFFF0000 >> 16)
    /* 595FC 80068DFC 24482101 */  and        $t1, $t1, $at
    /* 59600 80068E00 25400901 */  or         $t0, $t0, $t1
    /* 59604 80068E04 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 59608 80068E08 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 5960C 80068E0C 00000000 */  nop
    /* 59610 80068E10 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 59614 80068E14 0200A894 */  lhu        $t0, 0x2($a1)
    /* 59618 80068E18 0800A98C */  lw         $t1, 0x8($a1)
    /* 5961C 80068E1C 0E00AA84 */  lh         $t2, 0xE($a1)
    /* 59620 80068E20 004C0900 */  sll        $t1, $t1, 16
    /* 59624 80068E24 25400901 */  or         $t0, $t0, $t1
    /* 59628 80068E28 00480B48 */  mfc2       $t3, $9 /* handwritten instruction */
    /* 5962C 80068E2C 00500C48 */  mfc2       $t4, $10 /* handwritten instruction */
    /* 59630 80068E30 00580D48 */  mfc2       $t5, $11 /* handwritten instruction */
    /* 59634 80068E34 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 59638 80068E38 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 5963C 80068E3C 00000000 */  nop
    /* 59640 80068E40 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 59644 80068E44 0400A894 */  lhu        $t0, 0x4($a1)
    /* 59648 80068E48 0800A98C */  lw         $t1, 0x8($a1)
    /* 5964C 80068E4C 1000AA8C */  lw         $t2, 0x10($a1)
    /* 59650 80068E50 FFFF013C */  lui        $at, (0xFFFF0000 >> 16)
    /* 59654 80068E54 24482101 */  and        $t1, $t1, $at
    /* 59658 80068E58 25400901 */  or         $t0, $t0, $t1
    /* 5965C 80068E5C 00480E48 */  mfc2       $t6, $9 /* handwritten instruction */
    /* 59660 80068E60 00500F48 */  mfc2       $t7, $10 /* handwritten instruction */
    /* 59664 80068E64 00581848 */  mfc2       $t8, $11 /* handwritten instruction */
    /* 59668 80068E68 00008848 */  mtc2       $t0, $0 /* handwritten instruction */
    /* 5966C 80068E6C 00088A48 */  mtc2       $t2, $1 /* handwritten instruction */
    /* 59670 80068E70 00000000 */  nop
    /* 59674 80068E74 1260484A */  mvmva      1, 0, 0, 3, 0
    /* 59678 80068E78 FFFF6B31 */  andi       $t3, $t3, 0xFFFF
    /* 5967C 80068E7C 00740E00 */  sll        $t6, $t6, 16
    /* 59680 80068E80 2570CB01 */  or         $t6, $t6, $t3
    /* 59684 80068E84 0000AEAC */  sw         $t6, 0x0($a1)
    /* 59688 80068E88 FFFFAD31 */  andi       $t5, $t5, 0xFFFF
    /* 5968C 80068E8C 00C41800 */  sll        $t8, $t8, 16
    /* 59690 80068E90 25C00D03 */  or         $t8, $t8, $t5
    /* 59694 80068E94 0C00B8AC */  sw         $t8, 0xC($a1)
    /* 59698 80068E98 00480848 */  mfc2       $t0, $9 /* handwritten instruction */
    /* 5969C 80068E9C 00500948 */  mfc2       $t1, $10 /* handwritten instruction */
    /* 596A0 80068EA0 FFFF0831 */  andi       $t0, $t0, 0xFFFF
    /* 596A4 80068EA4 00640C00 */  sll        $t4, $t4, 16
    /* 596A8 80068EA8 25400C01 */  or         $t0, $t0, $t4
    /* 596AC 80068EAC 0400A8AC */  sw         $t0, 0x4($a1)
    /* 596B0 80068EB0 FFFFEF31 */  andi       $t7, $t7, 0xFFFF
    /* 596B4 80068EB4 004C0900 */  sll        $t1, $t1, 16
    /* 596B8 80068EB8 25482F01 */  or         $t1, $t1, $t7
    /* 596BC 80068EBC 0800A9AC */  sw         $t1, 0x8($a1)
    /* 596C0 80068EC0 1000ABE8 */  swc2       $11, 0x10($a1)
    /* 596C4 80068EC4 2110A000 */  addu       $v0, $a1, $zero
    /* 596C8 80068EC8 0800E003 */  jr         $ra
    /* 596CC 80068ECC 00000000 */   nop
endlabel MulMatrix2
    /* 596D0 80068ED0 00000000 */  nop
